keepassxc-browser/background/event.js
keepassxc-browser/keepassxc-browser.js
keepassxc-browser/popups/popup_login.js

Prevents multiple `page_clear_logins` commands. In some cases the credentals are already cleared and if `cip.initCredentialFields` is then called again the already retrieved credentials will be cleared from the popup_login.html.

Prevent multiple page_clear_logins

---

keepassxc-browser/manifest.json

Solves https://github.com/keepassxreboot/keepassxc-browser/issues/26.
This has a few limitations because of an older WebExtension API:
- Showing context menus on password fields (menus.ContextType)
- HTTP Auth support (webRequest.onAuthRequired)
User's should be notified for these if the wish to use Firefox ESR.

Add support to Firefox ESR

---

keepassxc-browser/keepassxc-browser.js

After jQuery update `.type()` was deprecated. This fixes the input type check. Previous method always returned `undefined`.
This also fixes issue https://github.com/keepassxreboot/keepassxc-browser/issues/22.

Fixes checking an input type

---

keepassxc-browser/popups/popup_functions.js

Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/21. Choosing credential fields now query the active window before getting the tabs. Before this always returned the last active tab ID which could've been in different window than the active one.

Choose credential fields works with multiple windows visible

---

keepassxc-browser/keepassxc-browser.js

Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/34.
StringFields were used in a old list format, not as standard JavaScript arrays.

Fixes the custom placeholders

---

keepassxc-browser/keepassxc-browser.js

Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/40.
If you have just the password field visible and you try to enter a password or TOTP manually the extension wanted to override the value with the credential password when losing the focus. This doesn't happen anymore.

Prevents password fill if input already has some data

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/background/page.js
keepassxc-browser/options/options.html

Adds a new option `Show notification also when new credentials are detected`. Earlier the only possibility to disable this (which can be an annoying notification) was to disable all notifications. This ensures that error notifications (see https://github.com/keepassxreboot/keepassxc-browser/pull/53) are still shown correctly even when login notifications are hidden.

Add a new option showLoginNotifications

---

keepassxc-browser/background/event.js
keepassxc-browser/keepassxc-browser.js

When doing a fill from context menu or from keyboard shortcut an alert is shown when multiple credentials are present. Instead of this alert show the user the autocomplete menu. If only password is filled the focus is changed to password input and only it is filled.
Also, all other alerts are removed and are showing a notification instead.
Solves https://github.com/keepassxreboot/keepassxc-browser/issues/52.

Remove alert and show autocomplete instead

---

keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup.js
keepassxc-browser/popups/popup_functions.js

This hides all popup elements by default. On some machines (for example slower virtual ones) certain elements flashed in the popup every time it loads.
Solves https://github.com/keepassxreboot/keepassxc-browser/issues/77.

Hide all popup elements by default

---

keepassxc-browser/keepassxc-browser.css
keepassxc-browser/keepassxc-browser.js

Multiple small fixes to the password generator:
- Center the `Bits` text and adjust the font to the input font size
- Modify z-index to the maximum so the password generator is always on top
- Change default `123 Bits` to `??? Bits`
Solves https://github.com/keepassxreboot/keepassxc-browser/issues/87 and https://github.com/keepassxreboot/keepassxc-browser/issues/107.

Password generator fixes

---

keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

When deleting the input field and pressing Save the default value is not saved. This ensures that in these cases the default value will be saved. Also a minimum values has been added to the input fields.
Solves https://github.com/keepassxreboot/keepassxc-browser/issues/106.

Revert to default values when saving empty input field

---

keepassxc-browser/manifest.json
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Alt+Shift+P doesn't work with Firefox. Changed the shortcut to Alt+Shift+I. Also show correct shortcuts for macOS in the settings page.
Solves https://github.com/keepassxreboot/keepassxc-browser/issues/72.

Modify shortcuts

---

keepassxc-browser/background/page.js
keepassxc-browser/keepassxc-browser.js
keepassxc-browser/options/options.html

Adds a new option `Save domain only` when saving new credentials. It is enabled by default.
Solves wishlist item https://github.com/keepassxreboot/keepassxc-browser/issues/85.

Added save domain only option

---

keepassxc-browser/background/keepass.js
keepassxc-protocol.md

With the current implementation (also valid for passifox/chromeipass/KeePassHTTP-Connector) searching from all databases returns entries also from non-connected databases. This change passes the connected database id's and key's to `get-logins`. A modified handling mechanism is needed to KeePassXC side that ignores non-connected databases based on this new array.
Solves https://github.com/keepassxreboot/keepassxc-browser/issues/83.
This PR can be merged after the KeePassXC side. Doesn't affect the functionality with the older releases.

Fixes search all databases

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/background/event.js
keepassxc-browser/background/httpauth.js
keepassxc-browser/background/init.js
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/global.js
keepassxc-browser/keepassxc-browser.js
keepassxc-browser/options/options.js
keepassxc-browser/popups/popup.js
keepassxc-browser/popups/popup_functions.js
keepassxc-browser/popups/popup_httpauth.js
keepassxc-browser/popups/popup_login.js
keepassxc-browser/popups/popup_remember.js

Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/57.
This PR changes the old `setInterval` based polling system to asynchronous one that triggers instantly when database related changes happen in KeePassXC. `setInterval` is not safe when using `browser.runtime.sendMessage` inside its scope. The memory heap keeps growing and garbage collector has never a chance to do its work.
Also, `use strict` is enabled in all scripts. This prevents the use of undeclared or accidental global variables.

Fix memory leaks

---

keepassxc-browser/background/event.js

Redetects credential fields automatically after reload. Closes https://github.com/keepassxreboot/keepassxc-browser/issues/90.

Redetect credential fields after reload

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/keepassxc-browser.js
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js
keepassxc-browser/popups/popup_remember.html
keepassxc-browser/popups/popup_remember.js

Settings page has a new tab `Ignored sites`. User has a possibility to add a certain site to this list from the popup icon or from the notification. When site is in the ignore list the credentials are still received but no notifications are shown for saving new credentials or modifying existing ones.
Closes the wishlist item https://github.com/keepassxreboot/keepassxc-browser/issues/95.

Add support for ignored sites

---

keepassxc-browser/background/event.js

If database is closed, remember popup or notification(s) are not shown when requesting new credentials.
Solves https://github.com/keepassxreboot/keepassxc-browser/issues/112.

Don't show remember popup if database is closed

---

keepassxc-browser/popups/popup.css
keepassxc-browser/popups/popup.html

Fixes hiding the KeePassXC update message from all popups by default.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/140.

Fix for hiding update message

---

keepassxc-browser/keepassxc-browser.js

Replaces the old `setInterval` based input field detection polling with `MutationObserver`. Now any new input fields shown are detected immediately.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/70.
Also solves input field detection for many other pages.

Improved dynamic input field detection

---

keepassxc-browser/keepassxc-browser.js

Removes one function call that is not used from content script initalization anymore.
Affects to #139 but probably not solves it.

Removed incorrect function call

---

keepassxc-browser/keepassxc-browser.js

Automatic addon of any username field caused unnecessary credential retrievals. Pages with a single username field it's preferred to use a manually choosed credential field.
Fixes #139.

Remove automatic username field add

---

keepassxc-browser/keepassxc-browser.js

Currently, this plugin produces quite a few exceptions in the browser's console when the observed list of changed nodes contains text nodes:
```
keepassxc-browser.js:1147 Uncaught TypeError: mut.target.querySelectorAll is not a function
at MutationObserver.<anonymous> (keepassxc-browser.js:1147)
(anonymous) @ keepassxc-browser.js:1147
```
This pull request fixes the issue by filtering out texts nodes from the list of mutated nodes.

Stop querying changed text nodes for children elements

---

keepassxc-browser/background/event.js
keepassxc-browser/background/keepass.js
keepassxc-browser/keepassxc-browser.js

Performs redetect credential fields on reconnect and does a database hash check when it has been changed or locked/unlocked.
Fixes #150.

Credential retrieval fix

---

keepassxc-browser/keepassxc-browser.js

With some pages MutationObserver tries to detect fields before browser extension settings are loaded. This fixes username field detection (e.g.) for pages: [https://accounts.google.com](https://accounts.google.com) and [https://login.live.com/](https://login.live.com/).

Improve detection of username fields

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/global.js
keepassxc-browser/keepassxc-browser.js
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Adds the following improvements to Ignored Sites:
When this is enabled the content script doesn't handle the detected input fields at all. No password generator icon or autocomplete will be initialized. Also, no credentials are retrieved from KeePassXC.
The page has a new input field for URL that will be added to the Ignored Sites list manually.
Under the hood `settings.ignoredSites` has been changed to Array.
Wildcards are supported by [match patterns](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns).
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/175.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/165.

Improvements to Ignored Sites

---

keepassxc-browser/keepassxc-browser.js

Ignores comment nodes before executing `getElementsByTagName()` to the element.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/183.

Ignore comment nodes

---

keepassxc-browser/keepassxc-browser.js

Checks if ignores sites settings already exists in its old Objects form, and replaces it with an array.
Fixes: https://github.com/keepassxreboot/keepassxc-browser/issues/192

Add check function for site ignore settings

---

keepassxc-browser/keepassxc-browser.js

An input field can be without any type. In these cases attributes returns `null`.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/197

Fix getInputs()

---

keepassxc-browser/keepassxc-browser.js

Fixes a regression introduced by #196.
Field detection stopped working for me entirely, since the `ignoredSites` setting is `undefined` and not `null`. Strangely enough, I cannot reproduce the original issue #192, which #196 was supposed to fix. So from my standpoint, #196 actually introduced the issue, causing the universe to implode in an endless loop of cause and effect.

Fix #196 regression: input field detection broken

---

keepassxc-browser/keepassxc-browser.js

Do not search inputs from targets that does not contain elements.
See [https://www.w3schools.com/jsref/prop_node_nodetype.asp](https://www.w3schools.com/jsref/prop_node_nodetype.asp).

Ignore nodes which does not contain elements

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/global.js
keepassxc-browser/keepassxc-browser.js
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Ignored sites settings tab is replaces with Site preferences tab. It allows to modify site specific settings. `Ignore form submits` is enabled by default. This PR also adds a feature for whitelisting pages with only a single username field visible, e.g. `login.live.com` or `accounts.google.com`.
Here's a preview [screenshot](https://i.imgur.com/I5F30BO.png).

Replace Ignored sites with Site preferences

---

keepassxc-browser/global.js
keepassxc-browser/options/options.js

Previously if manually added URL was in a form scheme://host and the last `/` was missing, the match pattern throws an error. This fix ensures that manually added URL's will be compatible.
Extends #208.

Match patterns fix

---

keepassxc-browser/background/event.js

Hides the update message of KeePassXC if the user has selected option `Never` from the settings.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/234.

Hide update message when updates are never checked

---

keepassxc-browser/options/options.js

Hides the connected key(s) partially in the Connected databases settings tab.
The first eight characters are shown. This enables the comparison with the key saved in KeePassXC without revealing it totally.

Hide the connected key(s) partially in the settings tab

---

keepassxc-browser/keepassxc-browser.js

Ignores any elements that don't have a className as a string. This includes SVG elements.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/209.
Fixes https://github.com/keepassxreboot/keepassxc/issues/2207.

Fix ignored elements function

---

keepassxc-browser/global.js
keepassxc-browser/keepassxc-browser.js
keepassxc-browser/options/options.js
keepassxc-browser/popups/popup.css

Adding URL to Site Preferences from a notification or from popup doesn't add the slash to the end of the URL if it's missing. Also, the function is moved to global.js because it must be accessed from the popup, options page and from content script.
Some CSS tuning regarding popup_remember.html was also needed.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/249.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/282.

Add slash to URL from notification button

---

keepassxc-browser/popups/popup_remember.js

When using context menu to save changed password the popup dialog is closed if no username is available.
This fix enables to use the username of the selected entry in the popup, and also disables the New button when no username is used for credential saving.
If user tries to update an old password (using the context menu from the old password's input field), a notification will be displayed and the popup is closed.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/211.

Fixed updating credentials from the context menu

---

keepassxc-browser/background/keepass.js
keepassxc-protocol.md

When doing associations to multiple databases within the same session, the same public key is used as an identification key. This causes the connections to use identical keys.
This PR solves it by modifying the keepassxc-protocol to allow a separate `idKey` used for association.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/257.
Related KeePassXC PR: https://github.com/keepassxreboot/keepassxc/pull/2185.

Allows a separate ID key for association

---

keepassxc-browser/keepassxc-browser.js

`isVisible()` checks if element is in the page. Previously the input field minimum size was 16 pixels, which is still quite large. This PR halves the value.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/262.

New values for element minimum size with isVisible()

---

keepassxc-browser/keepassxc-browser.js

When entering username manually, don't fill it automatically from the first autocomplete entry.
This fix doesn't fill the password field at all if the manually entered username is not one of the retrieved ones.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/288.

Fix entering username manually

---

keepassxc-browser/keepassxc-browser.js

Hides `Cannot find fields to fill in` error on username-only pages.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/290.

Handle single field login forms without error

---

keepassxc-browser/keepassxc-browser.js

Previously all input fields were accepted for processing the input type. Now all hidden input fields are instantly ignored before any further inspecting.
Some pages might have even a hundred hidden input fields with no use for the extension.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/292.

Filter out hidden input fields instantly in getInputs()

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

- Get current shortcut keys.
- Add button that opens shortcut page, it can be opened by using `chrome.tabs.create()`.
Hi everyone. Thanks for a great tool and extension. I decided to make some small improvements to the explanations for the shortcuts and also a button that opens the page in Chrome where you can configure the shortcuts.
Although `chrome://extensions/configureCommands` now redirects to `chrome://extensions/shortcuts`, I left it as the old URL to be more backwards compatible.
I tested this in Firefox, and getting the shortcut keys work as expected. It is now possible to customize the shortcut keys in recent Firefox versions, but it is not as easy as in Chrome, since the extension must provide an input field and then trigger the update.
Hope you like it!

Shortcut improvements

---

keepassxc-browser/background/httpauth.js
keepassxc-browser/background/keepass.js
keepassxc-protocol.md

When retrieving credentials from HTTP Basic Auth dialogs, an additional option is added to the request. KeePassXC side handles the permissions for HTTP Basic Auth separetely. If an older KeePassXC version is used, this extra parameter has no affect.
Related KeePassXC PR: https://github.com/keepassxreboot/keepassxc/pull/2542
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/273.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/342.
This requires KeePassXC 2.4.0 so merging this will have to wait.

Retrieve credentials with HTTP Basic Auth option added

---

keepassxc-browser/keepassxc-browser.js

The callback-based api will soon be removed. `webextension-polyfill` logs a warning in the console:
> Returning a Promise is the preferred way to send a reply from an onMessage/onMessageExternal listener, as the sendResponse will be removed from the specs (See https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage)

refactor: return a promise instead of using a callback function

---

keepassxc-browser/keepassxc-browser.js

Allows `type="TEXT"` and other not-so-standard cases.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/313.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/331.

Make input field type detection case insensitive

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/options/options.html
keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup_httpauth.html
keepassxc-browser/popups/popup_login.html
keepassxc-browser/popups/popup_multiple-fields.html
keepassxc-browser/popups/popup_remember.html

Removes the unnecessary whitespaces from translation file and inserts them in the HTML files instead. Glyphicons with appended text need an extra space inside buttons.

Remove whitespaces from translation file

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/icons/key.svg
keepassxc-browser/keepassxc-browser.css
keepassxc-browser/manifest.json
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html

Updates the old PNG key icon with a matching color SVG icon.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/324.

New key icon

---

keepassxc-browser/options/options.js

There's no need to disable new/modified logins when adding the site manually from extension settings. Modify the value to `Enable all features`.

Enable all features when adding site manually to Site Preferences

---

keepassxc-browser/background/event.js
keepassxc-browser/background/keepass.js
keepassxc-browser/keepassxc-browser.js
keepassxc-browser/popups/popup_httpauth.html
keepassxc-browser/popups/popup_login.html
keepassxc-browser/popups/popup_login.js
keepassxc-browser/popups/popup_multiple-fields.html
keepassxc-browser/popups/popup_remember.html

When locking the database from the popup lock icon the database hashed are not updated properly to the contect script.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/305.
Fixes https://github.com/keepassxreboot/keepassxc/issues/2480.
Also modifies the login popup to a locked state after clicking the lock icon.

Fix unlocking the database

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/background/init.js

Disables an unnecessary loop from `init.js` that is only used for blinking the extension popup icon. This caused constant CPU usage. It is moved to `browserAction.js` instead, and it's only used when needed.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/348.

Disable browserAction update loop

---

keepassxc-browser/background/keepass.js

By default, `keepass.compareVersion()` returns true if the version is greater or equal. In some cases it must not be equal, like when checking updates. This PR only extends the new comparison function.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/375.

Fix version comparison

---

keepassxc-browser/keepassxc-browser.js

Removes `aria-hidden` check from `cipFields.isVisible()`. Many pages don't respect setting the value correctly, and it's quite safe the remove from the checking function. It doesn't directly affect the element visibility after all.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/364.

Remove aria-hidden check

---

keepassxc-browser/keepassxc-browser.js
keepassxc-browser/manifest.json
keepassxc-browser/requests.js

Moves the `browser.runtime.onMessage` listener to a separate file that is loaded to content scripts with setting `all_frames=false`. Previously all keyboard and context menu shortcuts were executed in all frames. If the web page has several frames, the message listener is loaded several times, causing simultanous requests to KeePassXC (e.g. `retrieve_credentials`) which can cause race conditions.
Using the context menu or keyboards shortcuts must be handled only **once**.
A good example for this is the website [www.kayak.com](https://www.kayak.com). Previously, if the user wants to fill the username and password from the context menu, three simultaneous requests (one by each frame) will be made. Two of those are identical. The requests are:
- `https://staticxx.facebook.com`
- …

Fix race conditions

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/popups/popup.html

Modify the error messages to be a little more clearer.  The previous error messages are not clear enough to describe the error situation.
Related KeePassXC PR: https://github.com/keepassxreboot/keepassxc/pull/2622
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/261.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/312.

Clearer error messages

---

keepassxc-browser/keepassxc-browser.js

Added `Event.isTrusted` check for Autocomplete events which prevents page scripts for using any elements added to DOM.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/437.

Prevent page scripts to use events from added DOM elements

---

keepassxc-browser/keepassxc-browser.js

Fix for clearing the credentials when locking the screen.
Document visibility is hidden when the screen is locked. That kind of situation was not handled in the extension. The database hashes are updated only when the current document/page is visible. Now, when the document is hidden, all credentials are cleared just in case.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/357.

Clear credentials when the screen is locked

---

keepassxc-browser/keepassxc-browser.css
keepassxc-browser/keepassxc-browser.js

- Put the password generator icon in the background when autocomplete menu is active
- Simplify the isTrusted() function and prevent use of `undefined`

Minor fixes for release 1.33

---

build.js
keepassxc-browser/manifest.json
package-lock.json
package.json

Create separate manifest files for Firefox and Chromium based browsers. This makes possible to use SVG icons with Firefox version of the extension.
The build script reads the original `manifest.json` file's `version` and outputs .zip files with the version number included. It also modifies the content based on the browser:
- For Firefox all icons used are switched to SVG icons
- for Chromium the extra `applications` object is removed
To run the script, run: `node build.js`.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/25.

Create separate manifests using a build script

---

keepassxc-browser/css/autocomplete.css

Remove borders from autocomplete menu. It's a bit easier for the eye.
Before:
After:

Tiny fix for autocomplete.css

---

keepassxc-browser/content/pwgen.js

Prevents overriding `document.onclick` event and use event listener instead.
Fixes #486 
Fixes #481

Prevent onclick override

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/page.js
keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/css/autocomplete.css
keepassxc-browser/options/options.html

Adds option for Auto-submit when multiple credentials are present. It is **disabled** by default and ignored when auto-filling for single entry is enabled.
When the option is enabled, autocomplete menu shows the following:
Still. It's not guaranteed this works with every site.
Fixes #216.
Fixes #479.

Add option for auto-submit

---

keepassxc-browser/content/pwgen.js

Wrapping IntersectionObserver inside try/catch allows the content scripts to run even if the IntersectionObserver API is disabled. Firefox 52 (the minimum supported version) and some privacy adjusted `user.js` files for Firefox can stop the content script for running if this API is not found or disabled.

Wrap IntersectionObserver inside try/catch

---

keepassxc-browser/content/autocomplete.js

Fills only the password if autocomplete menu was used from a password field.
Previously with only-password pages it detected the password field as username and password field in the combination. That caused the extension to fill first the username, and the password only after that.

Fix autocomplete password fill

---

keepassxc-browser/content/keepassxc-browser.js

A few variables were not renamed during the merge of No jQuery branch. This broke the filling of String Fields.

Rename custom field variables

---

keepassxc-browser/content/keepassxc-browser.js

Type `username` for input fields is not from a HTML standard but it's still quite common, and it probably won't collide with other types.
Also fixed a small bug concerning credential filling from context menu or shortcuts.
Fixes #502.

Add username type as accepted input type

---

keepassxc-browser/content/autocomplete.js

Fixes the autocomplete with <kbd>Tab</kbd> so it does not fill any credentials if the username is not in the list. Previously this prevented filling another credentials via Auto-Type.
Fixes #497.

Fix autocomplete tab

---

keepassxc-browser/content/autocomplete.js

Fix using <kbd>Tab</kbd> with autocomplete menu.
The expected behaviour is that when you enter a username manually to the input field, using <kdb>Tab</kbd> will autocomplete the password when focusing away from the username field. Previously this didn't work correctly.

Fix using tab with autocomplete

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-protocol.md

Adds support for "expired" field in the protocol. If an entry has that property set, an extra string "[Expired]" is shown at the end of the entry title in the popup and autocomplete menu to inform the user.
KeePassXC side PR: https://github.com/keepassxreboot/keepassxc/pull/3134.
Screenshot:

Support for displaying expired credentials

---

keepassxc-browser/content/keepassxc-browser.js

Allow filling username using a keyboard shortcut when username field is the only visible one in the page.
For the Google page the DOMException was not handled correctly which caused the content script to fail.
Please note that if the page has scripts that include unhandled exceptions, keyboard shortcuts are only handled after those are thrown. This may require multiple uses of the shortcut, or wait till the page has loaded completely. Also, the input field must have focus.
Examples:
- https://accounts.google.com
- https://id.atlassian.com/login
Fixes solution 2. in https://github.com/keepassxreboot/keepassxc-browser/pull/520.

Allow filling username only from keyboard shortcut

---

keepassxc-browser/content/keepassxc-browser.js

Fix a typo in the code (from No jQuery PR) that prevented filling an option type when String Fields are used.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/553.

Fix filling option value

---

keepassxc-browser/content/pwgen.js
keepassxc-browser/css/pwgen.css

Add support for fixed entropy display with https://github.com/keepassxreboot/keepassxc/pull/3107. This PR also keeps it backwards compatible.

Add support for fixed entropy display

---

keepassxc-browser/background/event.js
keepassxc-browser/background/init.js
keepassxc-browser/background/keepass.js

Fixes the following reconnect issues:
- Reconnect didn't work if KeePassXC was started after the browser
- Clicking the popup was not reconnecting the extension properly
- Error message was shown if reconnected database was already open
FYI: When reconnect is active the extension consumes memory, but the garbage collector will clean it when the reconnect happens.
Fixes #523.
Fixes #544.

Fix reconnect issues

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/keepassxc-browser.js

Previous versions made changes to autocomplete that it is not always created, but a previously created autocomplete is reused. In some cases (for example Protonmail's mailbox password page) the input field inside autocomplete was still pointing to the previous page's username input field and caused invalid values filled to the password field.
Also in some cases username was filled along with the password, which not should happen.

Fix filling password from context menu

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/event.js
keepassxc-browser/background/init.js
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

- Removes reconnect from the popup (causes more problems than any good)
- Sets Auto-Reconnect to disabed as default
- Add a warning message to Settings page
- Fixes a connecting issue with KeePassXC versions earlier than 2.4.0
Fixes #562.

Remove popup reconnect

---

keepassxc-browser/content/keepassxc-browser.js

After a keyboard fill is made, focus to the input field (to password field if it's filled alone) to enable a form submit.
Fixes #571.

Focus to input field after keyboard fill

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/pwgen.js

Fix password fill when updating passwords with three different input fields (Current, New, Repeat new).
All password input fields are used in order, no matter which password generator icon is pressed. The fields are also filled in that order.
Fill uses the input field which icon has been clicked as active field. The next input field of the current one is always filled.
Fixes #575.

Fix password fill

---

keepassxc-browser/content/keepassxc-browser.js

Fixes the Update button disabling from Credential Banner.
Previously, after a page submit, even if `oldCredentials` had the credentials `kpxc.credentials` were used instead because it existed, but was an empty Array. Now `oldCredentials` are always used instead if it's defined.
Fixes #619.

Fix update button from Credential Banner

---

keepassxc-browser/content/keepassxc-browser.js

Adds `undefined` type to the accepted input field type's list. Extension's own `Element.prototype.getLowerCaseAttribute()` returns this instead of null.
Fixes #636.

Add undefined type to the input field list

---

keepassxc-browser/background/keepass.js

When a database is changed to a non-connected one, the association state is not updated properly. This fix resets the associated values and makes sure the next command (`keepass.testAssociation`) does it job.
Basically, the extension thinks a db has already connected when it's not.
Steps to reproduce without the fix:
1) Activate database tab, open the database and connect it
2) Open a second tab, open the database and try to connect it
3) `keepass.associate()` returns because it thinks the database is already associated
Fixes https://github.com/keepassxreboot/keepassxc/issues/2765.

Fix reseting association state

---

keepassxc-browser/options/options.js

Internal hashlist in `options.js` was not updated when connecting new databases. For example, if the table was empty, first connected database didn't appear to it correctly.
Also, a new bug was found with the following steps when keeping the Connected Databases page open:
1) Have two databases in KeePassXC, connect the first database
2) Switch to the second database, connect it
3) Remove the first database from the Connected Databases list
4) Switch back to the first database and connect it
5) The database shows an identical ID in the table even when it differs
Both of these are now fixed.

Update hashlist when connecting databases

---

keepassxc-browser/background/keepass.js

Using KeePassXC 2.5.0 with a database created with KeePassXC 2.5.0, decrypted messages from keepassxc-proxy contain an 'oldHash' and a 'hash' value that are equal. In that case, we must not try to replace the database hash ID in the keyRing, as it effectively leads to the keyRing entry to be destroyed without replacement.
This is a "regression" introduced with https://github.com/keepassxreboot/keepassxc-browser/commit/a2a7c20885f74d504e21f2850816d7fd31be8bff and only occurs when using KeePassXC 2.5.0 (currently in development) and a database which was created with KeePassXC 2.5.0 (2.4.3 binaries and database created with 2.4.3 even when used with 2.5.0 do have this problem). Only in that case the decoded proxy response contains the 'oldHash' value.
I don't know why that is the case. But …

Do not overwrite keyRing element with itself

---

keepassxc-browser/background/keepass.js
keepassxc-browser/options/options.js

Update icon shows a little green star for a newer version of KeePassXC even if the settings is set to "Never". Also, the Settings page doesn't update the radio button value correctly.

Ignore update icon if update check is set to never

---

keepassxc-browser/manifest.json

Removes the exclude for XML in the extension manifest. This was needed before when we were still using jQuery with content scripts (see #50). Current version is no longer affected by the issue.
Fixes #665.

Remove XML exclude from the manifest

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js
keepassxc-browser/manifest.json

Previously, handling multiple icons on a site was not working correctly. The icon Object(s) always referred to the last icon created, so hiding/showing them would only affect to the last icon.
Improvements:
- All icons are now created dynamically instead of a single Object.
- Added UsernameFieldIcon and PasswordIcon classes.
- Changed `kpxcPassword` to `kpxcPasswordDialog`, removing the icon handling from that Object
- Moved `IntersectionObserver` handling to `kpxcUI` and new `Icon` class instead of copying the same code.
To test this, you can create the following local HTML file:
```HTML
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<button id="nav1">Hide</button>
<button id="nav2">Show</button>
<section id="sec1" style="display:none">
<h1>Hidden</h1>
</section>
<section id="sec2"> …
```

Fix handling multiple icons

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/event.js
keepassxc-browser/background/page.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js
keepassxc-browser/css/totp.css
keepassxc-browser/icons/otp.svg
keepassxc-browser/manifest.json
keepassxc-browser/options/options.html

This is an extension to #617.
New features:
- Adds a new OTP icon for filling
- Adjusts icon saturation based on database lock status (password and OTP icons are grey)
When DB is locked:
When open:

Add TOTP icon filling and improve icon handling

---

keepassxc-browser/content/banner.js
keepassxc-browser/content/keepassxc-browser.js

When showing the new Credential Banner, checking the Site Preferences was able to return too soon and not check all the settings.
Instead, it's using the same `kpxc.siteIgnored()` that was implemented recently for another fix.
Fixes #626.

Respect Site Preferences settings with the banner

---

keepassxc-browser/content/ui.js

Function `kpxcUI.setIconPosition` doesn't take into consideration the direction of the page's direction. In RTL(right to left) websites, the icon is displayed on top of the text instead of the opposite side(left).
Fixes #701 .

Check document.dir to determine the position of the icon.

---

keepassxc-browser/background/page.js

Resets password filled state after page reload. This bug causes the icons not to show after a fill.
How to reproduce:
- Open any site you have credentials to with current `develop` branch.
- Fill any login
- Reload the page. Icons are no longer shown.
Related to changes made with https://github.com/keepassxreboot/keepassxc-browser/pull/625.

Reset password filled boolean state on page reload

---

keepassxc-browser/content/totp-field.js

Ignore TOTP icons if the field is too small

---

keepassxc-browser/content/banner.js

It's not possible to click on the ignore label in the banner, the reason is that the input tag of the checkbox doesn't have a id.
This PR adds an unique id and changes the "for" attribute.

Allow label to trigger ignore checkbox

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/page.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/options/options.html

- Fixes the incorrect text in the settings that only applies to Custom Login fields
- Adds a new option under credential saving that allows saving domain only (subdomains are included) instead of full URL
Fixes #736.

Add Save Domain Only option when saving new credentials

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/event.js
keepassxc-browser/background/init.js
keepassxc-browser/background/page.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/ui.js
keepassxc-browser/manifest.json
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Allows setting _Redirect allowance_ for the new Credential Banner.
The banner will disappear after the allowance count is met. Values can be set between 1-10. One is the default (form submit is count as one). Maximum is infinite, where the banner disappears only when user dismisses it.
A new permission `webNavigation` is required for the extension to identify redirect events.
Fixes #627.

Redirect allowance

---

keepassxc-browser/content/banner.js

Appends the Credential banner only to the main page instead of any iframes.
Fixes #695.

Show Credential banner only in the main page

---

keepassxc-browser/background/keepass.js

If Additional URL's are defined for the same site as the entry URL, duplicate entries returned from KeePassXC.
This fix removes any duplicate entries. Please note that this is only a workaround. The fix must be also done to KeePassXC where it must not return duplicates.
EDIT: Related PR for KeePassXC 2.6.0 https://github.com/keepassxreboot/keepassxc/pull/4288.
Fixes #761.

Remove duplicate entries

---

keepassxc-browser/content/banner.js

If user has defined the Root group for saving new credentials, and the default group KeePassXC-Browser Passwords doesn't exists, the default group is created.
This respects the user's choice and doesn't create the default group if there's no subgroups at all under Root. This bug was not visible if one or more subgroups existed.
Fixes #730.

Save to Root group if defined without default group

---

keepassxc-browser/content/keepassxc-browser.js

In some cases the submit button is not identified in the first round it's checked against `form.action`. This ensures the button will be returned later when inspecting all buttons inside a form.
Fixes #740.

Add submit button type to query with forms

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/page.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/ui.js
keepassxc-browser/options/options.html

The following changes are made to increase the performance:
- `MutationObserver` is completely disabled if all features are disabled for a site via Site Preferences.
- `MutationObserver` returns immediately if mouse button is pressed (drag'n drop).
- 'mousemove' event is always returned if mouse button is not pressed.
- `kpxc.initCredentialsFields()` accepts input field array directly from the target inspected by `kpxcObserverHelper.handleObserverAdd()` instead of parsing the whole document again.
- Doesn't iterate all the inputs for password generator icons when the option is disabled
- Restricts maximum simultaneous mutations to 200
- Added an option to disable the observer. When disabled, credentials can be only filled using keyboard shortcuts, using the context menu or the popup. …

Performance adjustments

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/banner.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js
keepassxc-browser/css/pwgen.css
keepassxc-browser/manifest.json

Moves all DOM elements to Shadow DOM.
Not originally meant as a security feature, but it adds a little more protection to the DOM elements extension is using. `Element.prototype.attachShadow` is overridden by the extension, so a page or a script cannot override it and make Shadow DOM visible. This makes receiving any usernames or other possibly sensitive information more difficult by malicious extensions or scripts.
Also, pages will no longer override CSS styles defined by the extension.
The downsides of this feature is that all CSS files must be included to the content scripts, and minimum Firefox version must be increased from 52 to 63. However, even the ESR release of Firefox is now at version 68.
Fixes #600.
Fixes #717.

Move DOM elements to Shadow DOM

---

keepassxc-browser/content/keepassxc-browser.js

The change: Do not add helpers on fields that have `autocomplete="off"` or `autocomplete="new-password"`. Identify fields with `autocomplete="one-time-code"` as TOTP fields.
Feel free to change things such as function naming, etc. I hope this PR is a good demonstration of what I am looking for. I used this MDN page: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
I think it would also be good to somehow be able to configure how aggressive the extension should be in trying to identify things. Sometimes I see the helpers on way too many fields and it would be nice to maybe have a "strict" mode option? Remember how browsers used to have (or still have?) a Quirks mode and Strict mode.
Anyhow, I hope you consider this. Thanks!

Use the autocomplete attribute as a hint

---

keepassxc-browser/content/banner.js
keepassxc-browser/content/keepassxc-browser.js

Final fixes for the next release:
- Don't show Credential Banner if the active database is not connected.
- Remove `autocomplete="off"` check added from #723. It causes problems with a lot of pages.
- Add unique ID's dynamically detected fields.
- Switch undefined `.length` check to `.size`.

Fixes for 1.5.5

---

keepassxc-browser/manifest.json

Windows and Linux enviroments are using the original shortcut `Alt+Shift+T` for opening the tools menu item. Changing the default shortcut for all OS's to `Alt+Shift+O`.
Fixes #759.

Modify TOTP keyboard shortcut

---

keepassxc-browser/content/totp-field.js

Ignores TOTP field icons when input field type is `password` or input field name/id begins with `zip`/`postal` and ends with `code`.
Fixes #768.

TOTP icon improvements

---

keepassxc-browser/options/options.html

The p works as space because  at gets spitted/closed&opened by the browser to no harm the design.
With change

Replace p with div as wrapper

---

keepassxc-browser/options/options.js

Theme switch & page reload is not working properly with Firefox. The new settings are loaded too soon.
Switched to Promise when saving settings, so it is more reliable for on-the-fly changes.

Fix theme switching with Firefox

---

keepassxc-browser/content/totp-field.js

Don't show TOTP icon on field types in the ignore list.
Fixes #797.

Add ignored types for TOTP field icons

---

keepassxc-browser/options/options.css
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

avoid overwriting some bootstrap stuff
Bootstrap uses min-width and not max because larger screen have usually more high-end PC and not a small smartphone. d-none and d-size-display overwrites it ad min-width.
```css
@media (min-width:768px){
```
Adjusted the max mediaquery, because it would match with min-width 768 from bootstrap on taht exact pixel.
Shrink you current git state to 780px or mobile size and you will get scrollbars because 160+col-md-10 has more width than 100% of your current window.
(Scrollbar is OS related - can be styled in last versions for windows and Linux. Not visible on some touch devices, but works with normal gestures)

Use bootstrap classes

---

keepassxc-browser/options/options.html

Instead of the help text, put the in/export into a separate card. it is no advanced setting.

Seperate card for In/Export

---

keepassxc-browser/background/keepass.js
keepassxc-browser/manifest.json
keepassxc-browser/options/options.js

If the hash already exists in the extension, the Created datetime is not updated properly. The connection is also not disconnected when the key is removed from the extension.
The manifest version bumb is made here, as this is the last PR for the new release.

 Update datetime on reconnect

---

keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

- Disables the Display group name option with older KeePassXC versions that don't support it
- Hides the warning if the version requirement is met

Disable group name settings with older versions

---

keepassxc-browser/css/autocomplete.css
keepassxc-browser/css/banner.css
keepassxc-browser/css/colors.css
keepassxc-browser/css/pwgen.css
keepassxc-browser/manifest.json
keepassxc-browser/options/options.css
keepassxc-browser/options/shortcuts.css
keepassxc-browser/popups/popup.css

Firefox will collide with CSS styles even if they are put to the Shadow DOM. Renaming the variables to non-generic names will prevent it.
Fixes #815.

Rename root CSS names

---

keepassxc-browser/options/options.js

With Firefox the settings are not properly saved before loading them again. Use a Promise version of the save to solve that.
Fixes #822.

Fix range input type saving with Firefox

---

keepassxc-browser/manifest.json
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

With the new theme, the button ID's were accidentally removed and the saving didn't work properly.
Fixes #827.

Fix default group saving

---

keepassxc-browser/background/keepass.js

Auto-reconnect fails with Windows if current KeePassXC version cannot be parsed.
Fixes #650.

Fix auto-reconnect with Windows

---

keepassxc-browser/content/keepassxc-browser.js

Ignore fields with CSS `opacity` 0.
Adds the old `kpxcFields.traverseParents()` back to the content script.
Fixes #850.

Check for CSS opacity

---

keepassxc-browser/content/totp-field.js
keepassxc-browser/content/username-field.js

Comparison `field.maxLength < 4` doesn't work properly when `maxLength` is greater than allowed value.
Also fixes an issue where the username icon would override TOTP icon.
Fixes #842.

Fix TOTP field maxLength comparison & do not override TOTP icon

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup_httpauth.html
keepassxc-browser/popups/popup_login.html
keepassxc-browser/popups/popup_multiple-fields.html

Removes the hard-coded text and replaces it with a valid translation.
Fixes #834.

Translate Lock database text

---

keepassxc-browser/_locales/en/messages.json

Improve the HTTP Basic Auth help text to clarify that single credentials are filled automatically. Also mention the possibility to enter credentials manually.
Fixes https://github.com/keepassxreboot/keepassxc/issues/4619.

Change HTTP Basic Auth help text

---

keepassxc-browser/background/event.js
keepassxc-browser/background/page.js

The Credential Banner could be shown on a wrong tab if switched quickly during a login/submit process.
Solution:
Store the tab ID to `page.submittedCredentials` object and compare the value before returning anything to the content script.
Fixes #860.

Ignore banner on tab change

---

keepassxc-browser/options/options.css
keepassxc-browser/options/shortcuts.css
keepassxc-browser/options/shortcuts.js

Previous CSS rules could cause white background with white text on some older Windows 10 releases. As the theme selection is already handled in `colors.css`, this fix removes the unnecessary `@media` rules.
It also fixes the manual theme selection with the Shortcuts page.

Simplify the options page CSS

---

keepassxc-browser/content/keepassxc-browser.js

Some pages make constant changes to the main HTML element via scripts. Ignoring changes directly to that element shouldn't break any sites, but some more testing might be needed.
`kpxcObserverHelper.getId()` also now generates an ID for the element based on its size, if no `classList` or `id` cannot be used.
Fixes #835.

Ignore main HTML element from MutationObserver

---

keepassxc-browser/_locales/en/messages.json

Changed the wording. Now it doesn't assume that there's a list above or below the info text, but it's more general without any hint to the possible UI.

Change the wording of connected databases text

---

keepassxc-browser/css/autocomplete.css
keepassxc-browser/css/notification.css

In pages based on purecss, the default letter-spacing is negative. This lead to
unreadable keepassxc entries in the autocomplete list and notifications.
This patch forces the letter-spacing and word-spacing to 'normal', and
text-rendering to 'auto', which is what purecss does in elements
displaying text.

Purecss compat - force letter-spacing

---

keepassxc-browser/content/keepassxc-browser.js

One simple check missing before displaying TOTP icon(s).
Fixes #889.

Check input field visibility for TOTP icons

---

keepassxc-browser/content/keepassxc-browser.js

- Adds `div[role="button"]` when detecting form buttons for credential submit.
- Traverses the parents when looking for `form`.
A good site for testing the feature: http://kingcowa.rbdigital.com/home
Fixes #891.

Add support for div role button with forms

---

keepassxc-browser/background/httpauth.js

KeePassXC uses QUrl for matching URLs against entries [1], so
standard-compliant URLs are needed.
[1] https://github.com/keepassxreboot/keepassxc/blob/9d2e066acae0cd7bd3447bf3c5fa8ff0c0c4f073/src/browser/BrowserService.cpp#L356
Tested on Firefox 76.0.1 with an HTTP proxy requiring digest authentication.

Fix retrieving credentials for authenticating against proxies

---

keepassxc-browser/content/keepassxc-browser.js

Sometimes form submit buttons are added outside the form, for example if a form is with ID `login-form` the button might have a property `form="login-form"` and it's not identified with a direct `querySelectorAll()` call to the form element itself.
Fixes #897.

Try to identify more form buttons

---

keepassxc-browser/content/keepassxc-browser.js

Full URL will be passed to KeePassXC instead of `document.location.origin` which doesn't include the URL path at all. This is required if we wish to do matching agaist paths in KeePassXC.

Pass full URL

---

keepassxc-browser/content/keepassxc-browser.js

#729 adjusted the `kpxc.initCredentialFields()` so it accepts dynamically added input fields as parameters. Those fields were not checked for visibility, so this can potentially be one reason why people have reported performance issues with the latest releases. It caused all input fields to be processed even if those were invisible, and possible caused `retrieve-credentials` requests without any reason.

Check visibility of dynamically added fields

---

keepassxc-browser/content/banner.js

If database has no groups and a default group is defined, it is not created properly. Instead the default group is created.
The fix allows for any group to be created if defined so, respecting the user setting.
Fixes #908.

Fix saving to a new group

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js

- Ignores TOTP fields if element `autocomplete` property defined as username, password or email field.
- Forces TOTP icon to show if defined via Custom Fields.
- Delete duplicate code and implement `kpxcUI.calculateIconOffset()`.
Fixes #900.
Fixes #907.

Improve TOTP detection and custom field overriding

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/username-field.js

Fix to a previous commit https://github.com/keepassxreboot/keepassxc-browser/commit/d36d4f4c36bc8873d4ce7ea1e597fb4ca0eb4d66#diff-412b80e8f63d0bb8ff5dcc811ec72823 where input fields were ignored if they were `readOnly`.
Now the fields are still accepted, but no icons or autocomplete menu is shown for them. This fix allows the `readOnly` input fields to be filled if they are specified as custom login field or a String Field.
Fixes #818.

Allow fill to readOnly fields

---

keepassxc-browser/css/banner.css

Makes the group selection div scrollable if the list is bigger than the content. Also affects to username selection when updating credentials.
The `max-height` is modified to percentage because with a fixed height the div cannot be scrolled if the content is larger than the browser window.
Fixes #917.

Make groups scrollable when saving new credentials

---

keepassxc-browser/content/banner.js

When using the Credentials Banner and selecting _Don't ask again for this site_ always saves an absolute URL which is prone to errors. The end of the URL might change depending on the situation/token/etc.
For example `https://mail.pasteur.la/?_task=login` saved to the Site Preferences no longer works with the main site. Instead, we are now saving the URL always with a wildcard appended after the last `/` (with the remaining deleted), so the final form is `https://mail.pasteur.la/*`.

Add wildcard to the ignored URL

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js

Fixes most of the high CPU usage with pages like music.youtube.com.
Changes made:
- Some special rules are added for the Youtube site
- Fixes an issue where elements in MutationObserver's `addedNodes` or `removedNodes` were using a `nodeType` which should've been ignored. The check for the target itself was clearly not enough.
- Any filling actions etc. to ignored site is forbidden via context menu or popup.
- Many checks have been altered in a way that the fastest checks are always done first.
- `IntersectionObserver` is no longer initialized automatically.
- `kpxc.passwordFilled()` is no longer requested multiple times.
- Any input field already holding some class starting with `kpxc` is ignored and not handled again.
- `kpxc.initCredentialFields()` is now divided with a new function …

Fix high CPU usage

---

build.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/manifest.json

Form input fields needs to be parsed correctly before sending them to `kpxc.handleCredentialFields()`. Otherwise the `data-kpxc-id` attribute will be missing from the inputs and those are ignored later.
Also removes unsupported `version_name` parameter from the Firefox build. Otherwise it always shows a warning in `about:addons`.

Parse input fields correctly before passing them forward

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/manifest.json

Calculating the document max size is not reliable with `document.body.offsetWidth` or `offsetHeight`. On some pages it might be zero. In these situations `document.documentElement.clientHeight` must be used.
Ensured that the maximum value is always used.
Fixes #936.
Fixes https://github.com/keepassxreboot/keepassxc/issues/5052

Fix document max size calculation

---

keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup_httpauth.html
keepassxc-browser/popups/popup_login.html

Makes the "You are using an old version of KeePassXC." message shown as a warning instead of an error.

Change KeePassXC update message from danger to warning

---

keepassxc-browser/content/keepassxc-browser.js

Username icon does nothing if _Automatically retrieve credentials_ is disabled from the extension settings.

Fix filling from username icon

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/banner.js
keepassxc-browser/content/define.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/manifest.json

- Add `name` and `placeholder` to `kpxcField.getId()`
- Don't override Custom Login Field variables in `kpxcFields.useCustomLoginFields()`
- Add missing `uuid` to Autocomplete when filling using keyboard.
- Respect Autocomplete Menu setting when filling using keyboard or Username Icon.
- Fix Auto-Submit (wrong function call).
- Fix Auto-Fill (e.g. with Google). The popup logins were also displayed incorrectly when this was enabled.
This also disables CSS animation support. This caused more problems than it solved. For some reason the event listener for it overrides the page's own scripts if those are handling `transitionend`. That should not happen, but both Firefox and Chromium does it for some reason, and there's no reliable way to call the "parent event" after our own handling.
WIP as …

Various fixes for 1.7.1

---

keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js

https://github.com/keepassxreboot/keepassxc-browser/pull/840 broke the icon position with right-to-left pages.
Also adds `text-align: right` and `dir=rtl` detection to Icon constructor.
Fixes #1019.

Fix relative icon position with dir='rtl'

---

keepassxc-browser/content/banner.js

KeePassXC versions lower than 2.4.0 does not support getting groups, and the result will be empty. This fix allows to save to the default group instead of just showing an error in the console.
Fixes #1016.

Save to default group when no group are found

---

keepassxc-browser/content/totp-field.js

Increases the maximum length of accepted TOTP field to 10. This ensures support with NextCloud, and other sites (AWS?) too.

Increase max TOTP field length

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/keepassxc-browser.js

Google login page has a submit button outside that form. Because this is one of the most common sites, a special handling is added to `kpxcForm.getFormSubmitButton()`. If we need some more special handling for certain sites in the future, we have to make an own function for these cases. For now, this one exception will do.
Fixes #802.

Fix Google login page submit

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/ui.js

The site https://www.biggerpockets.com/forums gives interesting results with the content script. `document.body` is not initialized at all until a short time has passed. The scripts don't handle that situation.

Add extra checks for document.body

---

keepassxc-browser/content/keepassxc-browser.js

A regression bug from the "big refactor". Input fields should be possible to fill using the keyboard even if an input field has not focus.
The first credentials are always filled when using this method. If the input field has focus and this is used, the Autocomplete List is shown instead.
Fixes #1053.
Fixes #1055.

Fix filling from keyboard without input field focus

---

keepassxc-browser/content/keepassxc-browser.js

New credentials saved from Credential Banner do not respect the Save Domain Only option.
Fixes #1044.

Fix Save Domain Only option with Credential Banner

---

keepassxc-browser/content/keepassxc-browser.js

Adds `input[type=submit]` to the list when checking form submit buttons. Also changes the behavior to look for the last possible submit button.
Fixes #1017.
Fixes #1070.

Add input with submit type

---

keepassxc-browser/content/totp-field.js

Adds some more strings to ignoreRegex. Fixes invalid TOTP detections for example with SoundCloud.
Fixes #855.
Fixes #1030.
Fixes #1039.

TOTP ignoredTypes fix

---

keepassxc-browser/content/totp-field.js

Removes `act` from `ignoreRegex` because it matches e.g. twoF**act**or, breaking Protonmail and possibly some other sites.
I'm not happy about this one. We really need to re-implement this whole accept/ignore TOTP in the future. Before that I will do any necessary tests for the Content Tests branch which includes 2FA fields from most common sites (and the ones we have had problems with), so we will have a possibility to quickly test any fixes.

Remove one TOTP ignore regex

---

keepassxc-browser/common/sites.js

Removes wildcards from subdomains to remove false positives from multiple sites.
Fixes #1089.
Fixes #1088.

Fixes for Predefined Sites

---

keepassxc-browser/content/keepassxc-browser.js

Certain pages with Chromium-based browser replaces `form.action` with an element instead of URL. It's unclear if this happens because of some script on the page or if it's a Chromium/Blink engine bug.
Fixes #1095.

Add extra checks for form.action

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/event.js
keepassxc-browser/background/init.js
keepassxc-browser/background/page.js
keepassxc-browser/content/keepassxc-browser.js

Adds a new option "Fill attribute…" to the context menu when String Fields are found with `KPH: ` attributes.
If multiple credentials use KPH attributes, a username is shown at the start of the attribute name.
Fixes #390.

Allow filling KPH attributes from context menu

---

keepassxc-browser/content/keepassxc-browser.js

Moves `isSearchField()` inside `kpxcObserverHelper.getInputs()` so search fields can be filtered out in one place instead of checking it in multiple functions.
Fixes username field icon with e.g. https://outlook.live.com.

Move isSearchField() to a better location

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js

Allows specific TOTP rules for certain sites, e.g. Amazon (which has `maxLength` defined as 20, which we normally ignore).

Add TOTP possibility to Predefined Sites

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/keepassxc-browser.js

If entry name exceeds 50 characters, it will be trimmed and `…` is added to the end. It fixes a problem where the Autocomplete Menu width can be wider than the page itself.
Fixes #1153.

Trim entry name in Autocomplete Menu when needed

---

keepassxc-browser/common/sites.js

Adjusts the site's Match Pattern URL to include only the signin page in any language (`/fi/`, `/se/`, `/de/` etc.).
Fixes #1139.

Adjust PayPal URL in Predefined Sites

---

keepassxc-browser/content/keepassxc-browser.js

If input field does not have focus:
- show autocomplete list if there are multiple credentials
- otherwise fill in credentials
Fixes #1081

Fix showing autocomplete list without input field focus

---

keepassxc-browser/content/totp-field.js

Checks the `placeholder` attribute for TOTP fields. Disables some false positives. Also adds `error` to the ignore list.
Fixes #1018.

Check placeholder attribute for ignoring a false positive with TOTP

---

keepassxc-browser/content/keepassxc-browser.js

If a form is not found on form submit or via exceptions (e.g. exceptions made for Google), include previously saved form to the list.
Partially fixes #1111.

Improve form handling with credential saving

---

keepassxc-browser/common/sites.js

Handle password input pages for all eBay domains with Predefined Sites, not just `.com`.
Fixes #1158.

Fix detecting eBay password input fields

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/keepassxc-browser.js

eBay detects the Apple ID button as submit button. Instead, we need to specify the first button of the form for this site.
Fixes #1160.

Fix Auto-Submit for eBay

---

keepassxc-browser/content/totp-field.js

Adds `twofa` to the accepted list. This fixes for example Protonmail's new page (current beta).

Add twofa as accepted TOTP field

---

keepassxc-browser/content/keepassxc-browser.js

Form buttons have `document.location.href` as a default `formaction`. If `formaction` is set, it will override the default `action`. Those buttons must be ignored.
Fixes #1192.

Ignore buttons with different formaction

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/manifest.json
package.json

Autocomplete related input field events got triggered more than once, causing Autocomplete menu to work incorrectly.
Fixes #1207.

Do not initialize Autocomplete input field events twice

---

keepassxc-browser/background/page.js
keepassxc-browser/content/banner.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/popups/popup.js

After user has saved new or modified credentials using the Credential Banner, new credentials are immediately loaded. This prevents the banner to reappear after the login and seeing the recently saved credentials as a new one. It also shows the updated credentials immediately in Autocomplete Menu and the popup login menu.
Fixes #1225.

Reload credentials after save

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/credential-autocomplete.js

If a web page has multiple login fields the Autocomplete Menu always shows only in the last of them. This fix adds an internal list to the class which can handle multiple menus without creating a new class for each one (which would be way too much).
Fixes #1244.

Add support for multiple menu locations

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/options/options.js

In some web pages the login page URL can first include only lowercase letters, but manually the same URL can have also uppercase letters. Site Preferences URL's are stored as case sensitive which breaks settings for such sites.
Fixes #1200.

Handle Site Preferences URLs as lowercase

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/init.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/manifest.json

Adds possibility to configure the following keyboard shortcuts:
- Save Credentials
- Choose Custom Login Fields
- Redetect Login Fields
- Reopen Database
Please note that there are no default key binding defined. This is because of restrictions with manifest.json files. Only four suggested keys per manifest are supported. For more information, see: https://developer.chrome.com/docs/extensions/reference/commands/
Fixes #732.
Fixes #839.
Fixes #993.
Fixes #1255.

Additional keyboard shortcuts

---

keepassxc-browser/content/define.js
keepassxc-browser/content/keepassxc-browser.js

Use XPath instead of a custom generated ID for HTML elements. New ID as XPath can be for example `/html/body/div/div/div[2]/div[2]/div[1]/div/div/form/div[4]/div[2]/input` so it doesn't care any names or classes, which might change dynamically, but relies on the page content and element ordering.
Fixes #1195.
Fixes #1233.
Fixes #1259.

Use XPath for element ID creation

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/page.js
keepassxc-browser/common/global.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/manifest.json
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js
package.json

Adds credential sorting to the extension. This makes KeePassXC's sorting in Browser Integration tab redundant and it must be removed for 2.7.0.
This feature adds four different options for the user:
- Sort matching credentials by title
- Sort matching credentials by username
- Sort matching credentials by group & title
- Sort matching credentials by group & username
Option page now has a combo box under the Autocomplete option:
Fixes #1217.

Add credential sorting

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/page.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Credentials are now cached in the background script. This can cause credentials to stay in the memory until database is locked or a tab is closed. Let's make sure all other credentials are cleared from other tabs after a switch.
The feature is using a timeout, which is a new option with default value of 10 seconds (range is 0-3600).

Make sure credentials are cleaned at tab switch

---

keepassxc-browser/content/autocomplete.js

#1248 broke this partially. The Autocomplete menu cannot be opened from the keyboard. It only works if it has been opened at least once using a mouse. With multiple menus supported, the input field must always point to the target element.
Fixes #1293.

Fix autocomplete menu with keyboard

---

keepassxc-browser/content/keepassxc-browser.js

Adds some extra checks for form's `id` and `name` elements. With Chromium-based browsers, those fields can actually be HTML elements, even referencing the input field itself.
Fixes #1289.

Fix id and name check for form

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/manifest.json
package.json

After adding the sorting to the extension, filling from popup can fill a wrong username. Releasing a new version after the merge. I want to get this fixed asap.
Fixes #1295.

Fix filling from popup

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/keepassxc-browser.js

eBay has a two-step login flow, and currently there has been some changes in the site. The password field was not detected correctly. It wasn't detected correctly either when re-logging, where username has been already filled, and user is prompted only with the password.

Improve eBay login flow

---

keepassxc-browser/content/credential-autocomplete.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/manifest.json
package.json

Switch from index to uuid when filling credentials/TOTP from previous page. With the new sorting system just an index is not a reliable way to handle data.
Fixes #1302.
Fixes #1303.

Switch from index to uuid

---

keepassxc-browser/content/keepassxc-browser.js

The comparison could return `undefined` instead of `true/false`. Lets make sure that doesn't happen.
Fixes #1316.

Fix Custom Fields check

---

keepassxc-browser/css/banner.css

I ran into a conflict on a site which also used a CSS animation named `slidein`, so I'd suggest this change or something like it to namespace the animation.  The `slidein` animation from this extension caused elements on the site to not appear.

add namespace to `slidein` animation

---

keepassxc-browser/background/init.js
keepassxc-browser/manifest.json
package.json

https://github.com/keepassxreboot/keepassxc-browser/pull/1283 probably broke the page reload and new credentials are not retrieved until a tab is closed and recreated.
This fix ensures credentials are cleared if user wishes to reload the page, causing a new access confirmation from KeePassXC.

Fix credential retrieval on page reload

---

keepassxc-browser/background/keepass.js

2.6.5 caused some confusion as the extension prompted for an update that actually wasn't released.

Ignore prereleases on update check

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/common/global.js
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Hello.
I wanted to block the extension from running on all `file://` URLs, but found that I was unable to do so. So here's a PR to make some changes to allow this.
I was actually able to just edit the input field with the browser's developer tools to add `file://.*` to the `pattern` attribute. But since `file://*` is 8 characters, I wasn't able to add it. I was able to change the `minlength` attribute, but there's also a JavaScript check that is harder to bypass (that is why I am removing the JavaScript check in this PR, since the `manualUrl.validity.valid` check already covers it). The JavaScript check actually requires 11 characters to pass (`value.length > 10`).
I was able to add a slightly longer URL though, `file:///users/*`, which should cover most of the local files I am going to …

Allow file:// protocol in site preferences

---

keepassxc-browser/content/keepassxc-browser.js

Apple login page uses `type=tel` for 2FA. Lets allow that.
Fixes #1362.

Fix filling TOTP on Apple login page

---

keepassxc-browser/content/keepassxc-browser.js

Firefox has sometimes problems setting `shadowRoot` to a proper object. Add an extra check that our `shadowSelectorAll()` is actually a function we are trying to use.
Fixes #1352.

Fix shadowSelectorAll check

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/ui.js

Does not allow forms or input fields with minimal opacity.
Fixes #1367.

Check for form opacity

---

keepassxc-browser/content/pwgen.js

Some websites check the strength of the password (and some also check if password and password-repeat are the same) with JavaScript (and block the form until the password is strong enough). Most of them listen to key-events to evaluate.
To make sure these websites accept the password filled out by keepass, I added more dispatchEvents to be triggered.

Added more dispatchEvents to fill()

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/ui.js

MutationObserver's form detection was not handling an `attribute` with `attributeName=style`.
Also found a exception where `document.scrollingElement` might not be set.
Fixes #1347.

Fix form detection from style attribute

---

keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/username-field.js
keepassxc-browser/manifest.json
package-lock.json
package.json

CSS files shouldn't be injected to every page via `manifest.json`. Injecting them to Shadow DOM works without it.
Fixes #1340.

Prevent CSS leaking

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/credential-autocomplete.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js

Use `stopPropagation()` to prevent event bubbling to the main DOM. These events should be only handled inside the extension.
Fixes filling for sites like https://qsuper.qld.gov.au/ and https://www.veikkaus.fi with dynamic popups/panels which normally close when they see a mouse click outside of the popup/panel.
Related (already closed) issue #1250.

Fix filling dynamic popups

---

keepassxc-browser/content/keepassxc-browser.js

Allow segmented TOTP fields if `type` is `text` and input fields has `maxLength` set to 1.
Fixes TOTP with for example https://app.hackthebox.eu/login.

Fix segmented TOTP with text type

---

keepassxc-browser/background/init.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/manifest.json

A simple addition for supportin a keyboard shortcut for reloading the extension. Because of the limit of predefined keyboard shortcuts is still four, user must set this manually.
Fixes #1418.

Add support for reload extension shortcut

---

keepassxc-browser/css/autocomplete.css

This makes long lists easier to use.
Look, I have way too many Google accounts. Opening the autocomplete list adds a scrollbar to the window which makes the experience less than stellar. I think it is better to scroll inside the list itself.
Before:
With this change:
250px was not scientifically picked, so let me know if you prefer another value.

Add scrolling to autocomplete list

---

keepassxc-browser/manifest.json
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Load the colorTheme earlier to prevent a white flash when the Settings page is opened. This requires storing the theme somewhere where we can load it immediately before the first render (I picked localStorage for simplicity).
My setup is: OS in light mode, KeePassXC-Browser in dark mode. I have only tested this in Chrome.
With this setup, there's a white flash when the settings page is opened up (test it by refreshing the settings page, which makes it very evident). The browser renders the page before the JavaScript has started running. A workaround is to have an inline script that blocks rendering and can apply the style before the first render. I had to add a `content_security_policy` for the inline script to run.
If someone can think of a more elegant way of doing this then please let …

Settings page: load the theme earlier to prevent a white flash

---

keepassxc-browser/content/autocomplete.js

Return early if there are no credentials. This fixes an annoying behavior where the extension selects the contents of a text field that does not contain credentials (e.g. misidentified TOTP field). Selecting the contents of a text field when it is clicked is not normal behavior and feels really off.
Example:
This text field is not a TOTP field and I am not sure why the extension thinks it is one. Clicking the icon gives me `Warning! No TOTP found.`
Even though no list appears, the contents of the text field is selected when I click the field. This is not something that I expect and it just feels really off.
Returning early fixes it for me.
I was about to also delete this code snippet, but it doesn't seem to have an effect in this particular case. Should it be changed as well? …

Do not select the contents of the text field when there are no credentials

---

keepassxc-browser/content/autocomplete.js

Hello.
This fixes an annoying issue which I have encountered a couple of times. If I want to use the KeePassXC Auto-Type feature and fill with the usual `{USERNAME}{TAB}{PASSWORD}{ENTER}` sequence, then if the browser extension happens to be connected to the database, it will mess it up when the Tab key is pressed, which results in the password being repeated twice and my login failing.
This simple fix resolved the problem for me.
Thanks for considering!

Do not autofill the password when Tab is pressed if the list is closed

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/totp-field.js

Twitter has changed their login flow to include only the username field. Also regognizing the 2FA field fails.
Added a new `kpxcSites.totpExceptionFound()` for special situations.

Add Twitter to Predefined Sites

---

keepassxc-browser/content/ui.js

Broken by https://github.com/keepassxreboot/keepassxc-browser/pull/1388. Seems `stopPropagation` interferes with page content. Just keeping it with `mouseUp` event works fine. Let's fix this asap.
Fixes #1446.

Fix interfering mouse events when dragging content

---

keepassxc-browser/css/autocomplete.css

Adds a minimum font size to the Autocomplete Menu. The default is still `.9em` but if it's smaller than `10px` we will use the latter. Fixes a site for example site https://www.teamblind.com/ where the font size is way too small to see properly.

Add minimum font size to autocomplete menu

---

keepassxc-browser/content/ui.js
keepassxc-browser/manifest.json

Something was missing from the latest CSS fixes. Notifications were not shown correctly, and an exception was not handled when attach was re-made to Shadow DOM.

Fix notification issues

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/manifest.json
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js
keepassxc-protocol.md

Adds a new command parameter for supportin favicon download after a credential has been saved.
An implementation is needed to the KeePassXC side. Let's keep this WIP until then.
Related KeePassXC PR: https://github.com/keepassxreboot/keepassxc/pull/7179
Fixes #86.

Add support for downloading favicons after saving a credential

---

keepassxc-browser/popups/popup.css

If a page has many credentials, the login list does not fit to the popup -> the whole popup becomes scrollable. Just the login list should scroll instead.

Scroll login list instead of the whole popup body

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/fill.js

Filling Google's login page password from the popup fails because the password field is actually in a recently detected combination. If there's more than one combination on Google's page, we must use the second one for a successful fill.
Fixes #1523.

Fix Google password fill from popup

---

keepassxc-browser/background/page.js

Instead of using one global `loginId`, save the variable to a tab related list.
Old `loginId` implementation breaks if during a login process (for example while waiting for TOTP) user goes to another tab and fills credentials, then returns to the previous tab and tries to do the TOTP fill.
Needs to be tested properly that it doesn't break anything.
Fixes #1420.
Fixes #1432.

Fix TOTP fill. Save loginId to tab.

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/browserAction.js
keepassxc-browser/background/client.js
keepassxc-browser/background/event.js
keepassxc-browser/background/httpauth.js
keepassxc-browser/background/init.js
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/common/global.js
keepassxc-browser/content/banner.js
keepassxc-browser/content/fill.js
keepassxc-browser/content/form.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/observer-helper.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/options/options.html
keepassxc-browser/popups/popup.js

Adds debug logging to the extension, mainly focusing on additional information on content scripts. Debug info contains all input fields detected on the page, plus the combinations sorted by the extension.
Option is disabled by default.

Add debug logging option

---

keepassxc-browser/content/fields.js

When the checkbox **Activate 2FA/OTP field icons.** in settings is deactivated, there are some cases, when green TOTP icon with bubble shows up. This fixes that behaviour.
There may be better places to put this check, but this works fine (although change in settings needs page refresh for TOTP bubble to show up).

Fix disabled OTP icons - they are never added

---

keepassxc-browser/content/totp-autocomplete.js

Found a bug where filling TOTP might not work in cases where the field is not regognized as a part of any current input field combination. In these cases the current input field is used.
This fix should allow filling TOTP to the field user has selected. Also, `await` was missing from the fill call causing `this.input` to be undefined in some cases.
Fixes.. probably a few TOTP bugs.

Fix filling TOTP to fields not in combinations

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/ui.js

Adds a new exception check in `sites.js` for icon position. Allows us making exceptions for other sites too when needed.
On Apple login page, their submit icon is directly under the extension Username Icon. This moves the icon a little bit so both are accessible.

Fix Username Icon position on Apple login page

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/content/fill.js

User should be notified when the filled password is longer than the input field actually accepts.

Add a notification when filled password length exceeds field's max length

---

CHANGELOG
keepassxc-browser/background/keepass.js
keepassxc-browser/manifest.json
package.json

The current extension version does not support launching the password generator with KeePassXC 2.7.0. This fix should support both KeePassXC 2.7.0 and older versions. With 2.6.6 and older, the extension's password generator should be shown instead.
Fixes #1586.

Fix password generator with KeePassXC version 2.7.0

---

keepassxc-browser/css/autocomplete.css

Can be reproduced with Apple login page https://appleid.apple.com/#!&page=signin where Autocomplete Menu items are a actually centered because of the global `body` style.
`text-align` is set to `start` so it's compatible with RTL.

Force text-align with Autocomplete Menu items

---

keepassxc-browser/content/fill.js

Additional fix to #1596. Input field's `maxLength` can be `-1` in some cases, which passes the current check and gives an incorrect notification.

Check that maxLength is above zero

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/event.js
keepassxc-browser/background/page.js
keepassxc-browser/popups/popup.css
keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup.js

Shows a link to the Getting Started Guide when there's no connection to KeePassXC. The alert can be dismissed, which also hides it permanently so it doesn't annoy anyone who is already familiar how the extension works.

Show a link to the Getting Started Guide for new users

---

build.js
package-lock.json
package.json

Updates the build script:
- Remove dependency to `fs` and `fs-extra`. Use NPM's own `npmcli/fs` instead
- Update package versions. Note that `file-url` is only used for tests.

Update build script

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/event.js
keepassxc-browser/background/page.js
keepassxc-browser/popups/popup.css
keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup.js

Shows a link to the Troubleshooting Guide every third time Reload fails when the popup is open. Hiding the alert prevents it appearing again.

Show alert link to Troubleshooting Guide when reload fails

---

keepassxc-browser/background/browserAction.js

Set icon to all tabs at once, preventing a flash from a previous/default state.
Fixes #1106.

Fix setting icon to all tabs

---

keepassxc-browser/content/keepassxc-browser.js

We are passing credentials requests from another domains to KeePassXC even if the content scripts are not allowed to work inside those frames. This can cause Access Confirmation requests to Google accounts, and can confuse users.
An excellent site to test this is https://twitter.com/ that loads a Google login button to the front page. Without the fix, a confirmation dialog for Google account should trigger when trying to fill username from the extension context menu.

Prevent Cross-Origin requests to KeePassXC

---

keepassxc-browser/content/observer-helper.js

Add support for detecting input fields inside child elements/nodes, including those inside Shadow DOM.
The new function does only a simple visibility check for the fields. Further checks are being made in `kpxcFields.getAllCombinations()`.
Fixes multiple sites mentioned in https://github.com/keepassxreboot/keepassxc-browser/issues/1358.

Add support for traversing child elements

---

keepassxc-browser/content/fill.js
keepassxc-browser/content/keepassxc-browser.js

Allows filling password manually from context menu or keyboard shortcut to an input field even if it's not part of any previously detected combination.
Looking at the source, there has to be some logical error in the implementation when filling using a combination. It returns the whole function if a combination is not found and never goes to line 62. Now the function for filling combinations is a separate one, which allows the function to continue even if combination detection fails.
Fixes #1574.

Allow filling password for non-detected fields and combinations

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/page.js
keepassxc-browser/common/global.js
keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Sort the page uuid first in the list. This is useful for pages that make you enter the username on one page and then the password on a second page (e.g. Google). You do not have to search for the same entry in the list again since it will conveniently be placed on top.
Since there are existing settings for sorting this list, perhaps a setting should be introduced for this behavior?
I've noticed that the TOTP list only lists one credential. I don't know exactly how that works under the hood, but perhaps it would be useful to only list the selected credential in this case too (but only when the password field is autocompleted)?
Please let me know if there's anything I should change.

Sort the page uuid first in the list

---

keepassxc-browser/background/init.js

This fixes a bug where two windows of the browser open and a user closes the last tab of a window. This sets the currentTabId to -1. Since the active tab of the remaining window does not change, neither onTabActivated nor onTabUpdated get called such that currentTabId stays at -1. This in turn causes `get_status` messages to fail such that the popup is not initialized properly (see attached screenshot).
I believe a better fix would to add `await browser.tabs.query({active: true, currentWindow: true})` to https://github.com/keepassxreboot/keepassxc-browser/blob/8beab0e7e8f1b9b8895bc83a9e4e08ee3728c5f1/keepassxc-browser/popups/popup.js#L153 and get rid of page.currentTabId entirely. Please correct me if im wrong, but from what i could tell so far it could be substituted with same approach …

Set currentTabId in remove tab.

---

keepassxc-browser/background/client.js
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/common/sites.js
keepassxc-browser/content/fields.js
keepassxc-browser/content/icons.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/observer-helper.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/popups/popup.css

Fixes few minor bugs found on first release test run:
- New upper row popup buttons are different height (Firefox)
- TOTP icon is gray in the second page even when credentials are filled (happened on Mastodon sites). Added a check for previously filled credential UUID. Also fixed UUID returning an integer when it should be string/undefined.
- Icon stayed gray if database was opened on one tab and switched to another tab that has credential. The icon states were updated too soon.
Fixes #1639.

Various fixes for 1.8.0 release

---

keepassxc-browser/content/observer-helper.js
package-lock.json
package.json
playwright.config.js
tests/content-script-tests.mjs
tests/global-setup.js
tests/global-teardown.js

With the new `node-fetch` it's impossible to mix using `require()` with ESM-modules (`file-url`), `import` must be used instead. Also fixed some other dependency problems and got rid of `fs-extra` in the setup and teardown scripts.

Update Playwright and fix vulnerabilities

---

keepassxc-browser/content/form.js

With some pages the extension detects both form submit and a submit button. When submit happens, two Credential Banner are created to DOM at the same time, and there's no reliable way to destroy them. The banner cannot be closed and stays on the page unless it's reloaded.
The bug can be reproduced every time when filling credentials to the login fields and pressing Sign On:
https://home.cards.citidirect.com/CommercialCard/login
Fixes #1656.

Prevent multiple simultaneous submits

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/observer-helper.js
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Due to some reports about reduced performance, the bottleneck is clearly the new more aggressive input field detection that traverses child elements (#1547). The feature is now purely optional, added to Site Preferences settings. Disabled by default.
Other changes related to this:
- Adjusted the help texts in Site Preferences tab.
- Changed checkbox background color on odd table rows. It wasn't visible at all with dark theme.
Fixes #1660.

Change Improved Input Field Detection as optional

---

keepassxc-browser/options/options.js

In Firefox 102.0, the version number was being incorrectly parsed as 10 rather than 102 because only 2 digits were being selected after the final "/"; so the button that enables navigation to the keyboard shortcuts page was being removed. This PR fixes that small bug.

Fixes a bug in Firefox where the Firefox version wasn't being correctly parsed

---

keepassxc-browser/common/sites.js

See #1672
```
https://www.paypal.com/cgi-bin/webscr*
https://www.paypal.com/checkoutnow*
```
Are URLs for checkout and express checkout sites.
`https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=XYZ&LocaleCode=de_XC` is an example express checkout URL
`https://www.paypal.com/checkoutnow?locale.x=de_DE&fundingSource=paypal&sessionID=xyz&buttonSessionID=xyz&env=production&fundingOffered=paypal&logLevel=warn&sdkMeta=xyz&uid=xyz&version=4.0.303&token=xyz&xcomponent=1` is an example regular checkout URL
```
https://www.paypal.com/*/signin*
https://www.paypal.com/signin*
```
Are URLs for regular login sites.
Closes #1672

Add more PayPal URLs to predefined sites

---

keepassxc-browser/content/ui.js

Checks `transitionend` event for `input` and `textarea` to update/hide the icons when needed. For performance reasons it's not necessary to check every element that receives the event.
Fixes #1478.

Fix icon position at transitionend event

---

keepassxc-browser/content/username-field.js

Disabling the Automatic Reconnect for 1.8.0 broke this feature. Now an extra step is added for reconnecting the extension.
Fixes #1675.

Fix reconnecting from username icon

---

keepassxc-browser/background/browserAction.js

When database was locked or unlocked, the `setIcon()` was using the tab's ID, overriding the global icon that is set when switching tabs. This caused the icon state to be invalid on these tabs where the database status change happened.
Fixes #1689.

Fix setting a global icon on database lock/unlock

---

keepassxc-browser/content/fields.js

Some webpages has hidden fields inside the segmented TOTP fields. Those should be ignored.
Fixes #1688.

Ignore hidden inputs with segmented TOTP fields

---

keepassxc-browser/content/fields.js
keepassxc-browser/manifest.json
package-lock.json
package.json

PayPal recently changed their 2FA page to a segmented fields. The form has six inputs plus a button as the last element. This is not currently supported.
Fix also bumps the version number.
Fixes #1703.

Fix PayPal TOTP

---

keepassxc-browser/content/username-field.js

After reconnecting to KeePassXC when clicking the Username Icon, fill is not made automatically.
Fixes #1680.

Fill after reconnect

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/fields.js
keepassxc-browser/content/fill.js

Steam also uses a segmented 2FA, but with five alphanumerics instead of six numbers. Some hard-coded requirements for the six char length is changed to a more dynamic implementation when doing the fill.
Needs to be tested properly. Steam locked my account temporarily when making the fix..
Fixes #1710.

Fix Steam TOTP

---

keepassxc-browser/background/keepass.js

Adding the new `requestID` is not reliable enough with older versions of KeePassXC. Sometimes the message sync just breaks. This needs to be added back with a version check after https://github.com/keepassxreboot/keepassxc/pull/8273 is merged.
If we have plans to merge that PR for 2.7.2, I'll add a version check already to this fix.
Fixes #1713.

Remove request ID for backwards compatibility

---

keepassxc-browser/content/fill.js

At some pages there's no combination detected for the TOTP. It should still be able to fill using the context menu.
Fixes #1649.

Allow filling TOTP without a combination

---

keepassxc-browser/common/global.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/username-field.js

Relevant issue #1727 
This PR adds calls to a `reconnect()` function when the following actions are fired
- `fill_user_pass_with_specific_login`
- `fill_username_password`
- `fill_password`
- `fill_totp`
The logic for `reconnect()` is identical to that which is used for the onClick listener on the username icon.

Automatically reconnect on keyboard shortcuts

---

keepassxc-browser/content/custom-fields-banner.js

In some cases other iframes are overriding the current field selection(s) during confirm.
Site for testing: https://www.aa.com/loyalty/login?uri=%2floyalty%2flogin&previousPage=%2fhomePage.do&bookingPathStateId=&marketId=
- When choosing only Username and Password fields, other iframe overrides the changes with empty values -> extension show's a warning that no Custom Login Fields are found.
- After fixing that Username and Password fields could be selected, but if a String Field is selected afterwards, it is overriden by an empty value -> only Username and Password fields are found from Custom Login Fields.
The fix makes sure there must be values before saving anything. Also removed an unused variable.
Fixes #1601.

Fix saving Custom Login Fields

---

keepassxc-browser/options/options.css
keepassxc-browser/options/options.html

Broken by upgrade to Bootstrap 5, hamburger menu properties are not updated. Also, the footer should be hidden when page width is too small to display it.
Fixes #1734.

Fix options page hamburger menu

---

keepassxc-browser/content/keepassxc-browser.js

In a use case where TOTP is retrieved from another database and credentials are "linked" during the fill, Autocomplete Menu on username field can show duplicate credentials, but the first one is with an empty password.
The fix makes sure the entry with an empty password is hidden if another entry with identical username is already found with a password.

Hide duplicate TOTP entry

---

keepassxc-browser/common/sites.js

Fix detecting submit button on Microsoft Login page

---

CHANGELOG
keepassxc-browser/css/colors.css
keepassxc-browser/manifest.json
keepassxc-browser/options/options.css
package-lock.json
package.json

On light theme checkbox background is set to a value that hides the checked/unchecked state on odd table rows. A new CSS variable is added to fix this.
Fixes #1720.

Fix checkbox colors on light theme

---

keepassxc-browser/background/keepass.js
keepassxc-browser/manifest.json
package-lock.json
package.json

If this parameter is added to the request, the extension requires it for reply, which is no longer used.
Fixes #1760.

Remove requestId from retrieve credentials request

---

keepassxc-browser/content/fields.js

This fixes TOTP input detection on epicgames.com's segmented input fields.

Update segmented TOTP detection to work with epicgames.com

---

keepassxc-browser/common/sites.js

I have missed a few URLs in #1673.
Example URL from ebay checkout
```
https://www.paypal.com/DE/cgi-bin/webscr?cmd=_express-checkout&token=XYZ&useraction=commit
```

Add even more PayPal URLs to predefined sites

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/css/autocomplete.css

When you use the autocomplete feature on the Google login page, using the enter key would trigger a form submit before the username is filled in and you would get the error `Enter an email or phone number`. The effect is a bit jarring.
`stopPropagation` needs to be called as well since Google probably has a key listener above the input element. I added a call to `stopImmediatePropagation` as well for good measure.
It would make sense to put this new `cancelEvent` helper function somewhere else since I think it should probably be used in other places where `preventDefault` is called.

Fix enter key issue on Google

---

keepassxc-browser/common/sites.js

Adds a new exception for `steamcommunity.com`'s 2FA page.
Fixes #1762.

Add steamcommunity.com to 2FA exception list

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/css/autocomplete.css
keepassxc-browser/css/colors.css

Introduced in https://github.com/keepassxreboot/keepassxc-browser/pull/1758 the Autocomplete Menu now has an extra border on dark theme. This removes it.

Fix Autocomplete Menu border color on dark theme

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/banner.js
keepassxc-browser/content/custom-fields-banner.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js

This fixes scrollbars appearing briefly on page load, and potentially causing the autocomplete menu to be shifted. I am experiencing this in Chrome. I tried to repro in Firefox but wasn't able to.
I have been trying to diagnose this weird offset issue a few times but haven't been able to figure it out until now. The autocomplete field would be offset like this on the Google sign-in page (but only the first time you opened the list!).
As you can see, the list is shifted slightly to the left for some reason. Closing the list and opening it again puts it in the correct position.
Putting a `debugger` statement in `updatePosition` reveals the problem. When the position is calculated, a scrollbar has appeared on the page. If you scroll down you will see that the autocomplete list is rendered at …

Wait for stylesheets to load before displaying shadow DOM elements

---

keepassxc-browser/content/totp-field.js
tests/assert.js
tests/tests.js

If input field has `autocomplete=one-time-code` set, it should be accepted whatever the settings are.
Fixes #1785.

Always accept one-time-code TOTP field

---

.eslintrc
package-lock.json
package.json

`eslint-config-airbnb-base` has a dependency to `eslint-plugin-import` which has a vulnerability and the library hasn't been updated in 9 months. ESLint rules are now extending the built-in `eslint:recommended` ruleset.
Fixes https://github.com/keepassxreboot/keepassxc-browser/security/dependabot/6.

Remove eslint-config-airbnb-base

---

keepassxc-browser/background/event.js
keepassxc-browser/background/page.js
keepassxc-browser/popups/popup_functions.js
keepassxc-browser/popups/popup_httpauth.js
keepassxc-browser/popups/popup_login.js

Removes the `browser.runtime.getBackgroundPage()` request from the popup code. It's slightly cleaner and directly compatible with Manifest V3 where the runtime function is no longer allowed.

Remove browser.runtime.getBackgroundPage()

---

keepassxc-browser/content/keepassxc-browser.js

This makes the extension behave as expected in my set up, where unlocking the primary DB (which unlocks the child DBs automatically) keep the extension in an "unlocked" state.

Fix extension behavior for Auto-Open

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/background/keepass.js
keepassxc-browser/popups/popup_httpauth.html
keepassxc-browser/popups/popup_login.html

Fixes the old annoying bug that shows this kind of popup if you switch from open database to a closed one, and the open database had credentials:
This change also fixes the position of "Reopen database" buttons after database lock has been made from the popup icon.
Steps to reproduce:
1. Have two databases in KeePassXC, open the first one.
2. Go to a page where the open database has credentials.
3. Switch from KeePassXC to the closed database.
4. The extension popup shows no login data, and no error is shown.

Fix login popup change with locked database

---

keepassxc-browser/content/observer-helper.js
keepassxc-browser/content/ui.js

Ensures that input fields that have gone hidden will have the icons removed. The check is now also made when just adding new elements to the page.
Without the fix using the following site leaves the Username Icon visible on the email field even if Next is pressed:
https://prium.github.io/phoenix/v1.8.0/modules/forms/wizard.html
Fixes #1833.

Remove icon input field from the internal list when removing the icon

---

keepassxc-browser/background/event.js
keepassxc-browser/background/keepass.js

Sometimes a strange bug can occur where `checkUpdateKeePassXC` setting is saved as a string. It should be made sure that only integers are used when making comparisons.
The actual bug where saving the setting as string has not been caught.
Fixes #1832.

Make sure checkUpdateKeePassXC is an integer

---

keepassxc-browser/content/banner.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/username-field.js

Improves the filling from Username Icon on multiple situations:
- Fill when KeePassXC is connected but database is unlocked.
- Fill when KeePassXC is not connected and database is unlocked.
- Fill when KeePassXC is not connected and database is locked.
Previously the code relied on `check_database_status` for checking if the database is open, but that should not be used. Especially when the new implementation for database handling is implemented in the future, KeePassXC can return database hash also from locked databases. Instead we should check the `kpxc.databaseStatus` which already has the up-to-date information.
When database is locked when using the Username Icon, a Manual Fill is requested. It's performed after the database is unlocked. In some situations the first page triggering …

Improve filling from Username Icon

---

keepassxc-browser/content/form.js

Try harder to identify the username used if the user have multiple entries for a website. This should help prevent false-positive banners when the user did *not* change their password, especially on multi-step login forms.
This has been a long-standing annoyance for me but I haven't really understood why it happens. Happens every time if you have multiple entries for a page _and_ the website is using a multi-page login form.
I tested this on https://odysee.com/ and I confirmed that the banner still showed up when I actually changed my password.
I was also considering changing
```javascript
if (kpxc.credentials.some(c => c.login === usernameValue && c.password === passwordValue)) {
```
to
```javascript
if (kpxc.credentials.some(c => (!usernameValue || c.login === usernameValue) && …
```

Try harder to prevent false-positive password change banners

---

keepassxc-browser/content/fill.js
keepassxc-browser/content/keepassxc-browser.js

Fixing a regression for #818 from change #1841. Filling `readonly` fields should be allowed if those are specified as String Fields using Custom Login Fields. That's the only exception. No username/password/totp will be allowed to do that.

Allow force-fill to String Fields even if readonly

---

keepassxc-browser/background/event.js
keepassxc-browser/background/page.js
keepassxc-browser/manifest.json
keepassxc-browser/popups/popup_httpauth.js
package-lock.json
package.json

https://github.com/keepassxreboot/keepassxc-browser/pull/1822 broke Basic HTTP Auth. Old `browser.runtime.getBackgroundPage()` allows Promises to be inside objects, but `sendMessage()` does not. The credentials selected for HTTP Auth must be passed to the background script for resolving the Promise correctly.
Fixes #1868.

Fix HTTP Auth fill

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/custom-fields-banner.js
keepassxc-browser/content/ui.js
keepassxc-browser/manifest.json

With some webpages `document.scrollingElement` or `document.documentElement` are not providing correct `scrollTop` and `scrollLeft` values. Instead `document.defaultView` is used with `scrollX` and `scrollY` values.
Needs a little more testing to ensure this doesn't break any sites with scrolling.
Fixes #1872.

Use defaultView instead of scrollingElement when positioning icons and menus

---

.eslintrc
keepassxc-browser/background/browserAction.js
keepassxc-browser/background/client.js
keepassxc-browser/background/event.js
keepassxc-browser/background/init.js
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/common/global.js
keepassxc-browser/common/sites.js
keepassxc-browser/content/banner.js
keepassxc-browser/content/custom-fields-banner.js
keepassxc-browser/content/fields.js
keepassxc-browser/content/fill.js
keepassxc-browser/content/form.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/manifest.json
keepassxc-browser/popups/popup.js
keepassxc-browser/popups/popup_functions.js
keepassxc-browser/popups/popup_httpauth.js
keepassxc-browser/popups/popup_login.js

Various code cleanups:
- Use `??=` and `&&=` assignments where it clears up the code.
- Use optional chaining `?.` instead of `if (value && value.something)` comparisons.
- Use `Object.hasOwn()` instead of `hasOwnProperty()` in some cases.
- Use negative indexing `.at(-1)` instead of `arr[arr.length — 1]`.
- Use simplified for loops when index is needed.
- Refactor default settings to use a loop based setter.
The Firefox minimum version must be increased to 91, which is the current max version Debian stable provides.

Code cleanup for 1.8.6

---

keepassxc-browser/background/event.js
keepassxc-browser/common/sites.js
keepassxc-browser/content/custom-fields-banner.js
keepassxc-browser/content/keepassxc-browser.js

Instead of unsafe `postMessage()` all messages between iframes should be transferred using `sendMessage()`.
For this a new event `frame_message` is added to `event.js` which only bounces the message back to the current tab's frames. After that `keepassxc-browser.js` handles the internal message (`frame_request_to_frames` or `frame_request_to_parent`) and calls the correct functions based on top window or iframe status. It's possible to use the same `frame_message` for other similar situations in the future.

Transfer iframe messages without postMessage()

---

CHANGELOG
keepassxc-browser/manifest.json
package-lock.json
package.json

For tomorrow's release. Switched the changelog to use YYYY-MM-DD.

Update version and changelog for 1.8.6

---

keepassxc-browser/content/icons.js

In some rare cases form can contain non-standard properties (for example a HTML element in `form.action`) which causes the extension to ignore the form and it will be not added to `kpxcForms.savedForms` and submits are not listened. Combinations from these forms are ignored later when trying to create Username Icons.
The fix ensures that if an internal form struct has a `form` defined but it's not in `savedForms`, the Username Icons are still added to DOM normally.
Fixes #1900.

Fix adding Username Icon to non-identified forms

---

keepassxc-browser/content/fill.js

Adds a new notification when logins are not found a site and fill is done using the Username Icon or context menu. The domain URL is added to the message, clarifying a situation where the login URL can differ from the one user has set. For example `https://www.gog.com` instead of `https://login.gog.com`.
Fixes #1927.

Add a notification with domain URL when logins are not found for a site

---

keepassxc-browser/background/page.js

When using a Tab Restore feature or loading a page from a bookmark folder to the background, credential requests are still sent to KeePassXC. The fix makes sure a tab needs to be active before any requests are made.
Storing the `tab.id` allows retrieving credentials from the same URL even if a tab was closed and reopened right after.

Prevent retrieving credentials from background tabs

---

keepassxc-browser/options/options.html

Adjusts the About page in the options:
- Change contributors to a list
- Add new contributors to the list
- Move extension version information to the top
- Remove some extra line changes to make the page more compact
- Checked the Patreon supportes list (no new additions)

Adjust contributors list and About page

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/background/keepass.js
keepassxc-browser/options/options.js

Use the icon with `!` when a connection to KeePass database is needed. Previously just the default icon was used, that does not show the status correctly. There should be some kind of indication for the non-connected state.

Use bang icon when connection is needed

---

keepassxc-browser/background/client.js

If there's an error message returned when waiting for response, the listener should be destroyed. Applies at least to Password Generator widget when it is closed and an error message is received.
Some more testing needed to ensure this doesn't break anything.

Handle errors properly when waiting for response

---

keepassxc-browser/content/observer-helper.js

Loosens up the rules slightly for Improved Field Detection:
- Use `ignoredNode()` check instead of `ignoredElement()` to allow `#document-fragment` nodes to be parsed.
- Use `child.childNodes` directly, and store input fields to a separate array.
Related PR, but not entirely solved: #446. Fixes other Shadow DOM sites, e.g. https://account.here.com.
Fixes #1904.

Adjust Improved Field Detection

---

keepassxc-browser/content/fields.js
keepassxc-browser/content/keepassxc-browser.js

Fixes a few bugs related to credential saving from context menu:
- No notification is shown if database is closed.
- If Custom Login Fields have set to the page, combination is not found because it is bound to the active element `type`. This is not needed because the combination array already includes the input elements correctly.

Fix getting combination from Custom Login Fields during credential save

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/credential-autocomplete.js
keepassxc-browser/content/totp-autocomplete.js

When the visible Autocomplete Menu list is sorted, the internal non-sorted list is still used for credential filling with an index when pressing Enter. Instead, the selected item and it's UUID must be used.
Fixes #1917.

Fix Autocomplete Menu fill on Enter when list is sorted

---

keepassxc-browser/content/fill.js

If Autocomplete Menu is disabled from the extension settings, only active element is filled with username or password, not the whole combination.
Note: Filling only the active element should be done only if a combination is not detected at all (for example single username field that is not automatically detected).
Fixes #1973.

Fill whole combination when Autocomplete Menu is disabled

---

keepassxc-browser/background/event.js

When clicking "Check for updates" button from the settings page, the current KeePassXC version object is not parsed correctly, showing the version as empty string.

Fix Check for updates button response

---

keepassxc-browser/content/ui.js

Pages with iframes sometimes fail to remove notifications from inside the frames. There are two possible failed situations this PR fixes:
- Notification is inserted inside iframe, but is removed from the parent instead.
- Notification is inserted to the parent but is removed from the iframe.
The behavior can be clearly seen on https://www.paivyri.fi if credentials are filled from the context menu when database is closed.

Fix removing notifications

---

keepassxc-browser/background/client.js
keepassxc-browser/background/keepass.js
keepassxc-browser/manifest.json

This change refactors the way messages and stored to the message buffer, and how the response message is being waited and handled.
Previously the extension created a new listener for every command sent via `.addListener()`, and after a proper response `.removeListener()` was used after a response. In some cases the response is not received, or there is only a generic error message available that cannot be identified as a response to any message. When these messages (and listeners) pile up, the extension will be shown `Nonce compare failed` error messages and the connection to KeePassXC might get broken. In thise case KeePassXC' native messaging handler can show multiple messages waiting inside one socket message, and the messages are not handled properly.
This is been fixed by creating a …

Refactor extension messaging

---

keepassxc-browser/content/keepassxc-browser.js

Some pages are not accepting filled username or password even if all needed events are dispatched.  Ensuring that the element is focused and legacy/deprecated type of events from `createEvent()` might be needed before the changed value of the input element is accepted.
Can be tested on: https://banking.postbank.de/#/login
Fixes #1984.

Dispatch more events on fill

---

keepassxc-browser/content/fill.js

Find the active element from the combinations list instead of just returning the first value that has username or password fields. There can be multiple combinations detected from a page.
Can be tested using https://banking.postbank.de/#/login

Use active element on fillFromCombination()

---

keepassxc-browser/content/fill.js

Addition to #1985. Previously we only selected the first combination, and the fix changed the method to select the one with the active element. Both scenarios should be supported: if the active element is not found in the combination (something else than the input field is selected when trying to fill using keyboard shortcut), select the first combination instead.

Use the first combination if active element is not found

---

keepassxc-browser/content/fill.js

The `credentialList` can be `undefined`. In that case the error notification is now shown at all.

Fix showing TOTP error message

---

keepassxc-browser/background/client.js

Let's move `cancelTimeout()` inside the message buffer handling, so it's not needed in `handleNativeMessage()`. Timeouts should be canceled automatically.
Related to #1999.

Move cancelTimeout() to the messageBuffer

---

keepassxc-browser/content/autocomplete.js

When opening Autocomplete Menu from keyboard while pressing <kbd>Down</kbd>, the Autocomplete Menu opens but the first item is not selected. If user presses <kbd>Down</kbd> again, the second item is selected normally.

Fix selecting first item on Autocomplete Menu open

---

keepassxc-browser/content/passkeys-utils.js

Some sites omit `attestation` and `userVerification` even if all other fields in the public key are correct. In this case revert to default values:
- `attestation: none`
- `userVerification: preferred`
Fixes #https://github.com/keepassxreboot/keepassxc/issues/10050

Passkeys: Revert to default values

---

keepassxc-browser/common/sites.js

Wordpress' login page has a dynamic password field, plus a single username field. Those are not detected at all by default.

Add Wordpress to Site Preferences

---

keepassxc-browser/content/passkeys-utils.js

`hostname` should be used instead of `host`. The latter can contain port information that causes Relying Party to be ignored.

Passkeys: Use hostname instead of host

---

keepassxc-browser/popups/popup.css
keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup.js
keepassxc-browser/popups/popup_functions.js
keepassxc-browser/popups/popup_httpauth.html
keepassxc-browser/popups/popup_httpauth.js
keepassxc-browser/popups/popup_login.html
keepassxc-browser/popups/popup_login.js

Firefox 106 has fixed the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1786587) where the popup was smaller size than the normal one, when it was moved to overflow menu in Firefox's toolbar. The special handling for popup size is now removed.
Previously fixed in: https://github.com/keepassxreboot/keepassxc-browser/pull/1571.
Related issue: #721.
This should be merged only after Firefox ESR has the fix. Keeping the WIP state for now.

Remove special handling for Firefox overflow/hamburger menu

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/banner.js
keepassxc-browser/content/custom-fields-banner.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js

This UI issue is easy to reproduce on https://example.com/. That website applies styles to all `div` elements, which includes our wrapper div elements.
If you open the custom fields toolbar on that page then you will see a second white bubble appear at the bottom. This is our wrapper div. By setting <code>[all](https://developer.mozilla.org/en-US/docs/Web/CSS/all): [unset](https://developer.mozilla.org/en-US/docs/Web/CSS/unset);</code> we stop the page's styles from applying to this element.

Stop pages from being able to style the shadow DOM wrapper div element

---

.eslintrc
README.md
keepassxc-browser/background/client.js
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js
tests/.eslintrc
tests/content-script-tests.mjs

Hello, I'm back with some small fixes that I have accumulated over a few months.
It was possible to get the "empty message row" to show up when having things in the table, for example in the list of connected databases. If you add your first connection from the options page then you'll get this:
So I rewrote the logic that hides the row in pure CSS, which makes the code much cleaner and fixes this bug.
---
I removed `table-bordered` from the tables since I think it gives the pages a cleaner look. Here's the before/after:
Hopefully you like this look better too. 😄
---
Also fixed some other things, please see the commit messages for more details. Let me know if you want me to change anything.

Small fixes to the options page

---

keepassxc-browser/background/event.js

Broken since 1a218573e7d26b5c7f95d4902f657c081c5418d4.

Fix `keyId` not showing in popup

---

keepassxc-browser/common/sites.js

According to a user, barmer.de is quite popular site in Germany. The submit button in the password page is not detected correctly. All buttons have identical properties, so the parent element must be identified first.

Add barmer.de to form submit button exception list

---

keepassxc-browser/content/pwgen.js

When generating a new password using KeePassXC's password generator, the next password field is not filled.
Fixes #2066.

Fix filling next password field with password generator

---

keepassxc-browser/options/options.js
keepassxc-protocol.md

Changes the required minimum version of Passkey support from KeePassXC 2.8.0 to 2.7.7.

Lower the required KeePassXC version for Passkeys

---

keepassxc-browser/content/passkeys-utils.js

If `authenticatorSelection` is found from the public key, but `userVerification` is missing, set it to the default value `preferred`.
Fixes #2033.

Passkeys: Set userVerification to default value if not found

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/page.js
keepassxc-browser/content/fill.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/options/options.html

Adds a new option for enabling auto-fill for TOTP if a single credential with TOTP is found.
Fixes #728.

Add option to fill TOTP automatically

---

README.md
keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/event.js
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/common/global.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/manifest.json
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js
keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup.js
tests/tests.js

Adds support for checking Top-Level-Domains from hostnames, and returning a base domain. The implementation is almost similar to KeePassXC's https://github.com/keepassxreboot/keepassxc/pull/9935 that is using a cookie API for TLD's (there's no direct API for it).
If a Cross-Origin iframe is detected, the popup will show a new option:
Pressing the button will add the tab/window URL to Site Preferences and enables the new "Allow Cross-Origin iframes" option.
Content script's `isIframeAllowed()` now performs the following:
- Checks if Cross-Origin iframes are allowed by Site Preferences.
- Checks the base domain of window/iframe using TLD list.
- Allows the iframe automatically if it's under the same base domain.
- Disallows iframes that do not match with the tab's/window's URL.
Unit tests …

Add support for TLD check and allowing Cross-Origin iframes option

---

keepassxc-browser/content/fill.js

Username field should not be cleared if the entry has no username set.
Fixes #2105.

Do not clear the username field if the entry has no username set

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/content/fill.js

When filling password from a keyboard shortcut or from a context menu, plain text fields should not be filled. When Custom Login Fields are used and the input element is specified as a password field, then the fill is allowed.
Fixes #2102.

Do not allow filling password (only) to plain text fields

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/client.js

Non-Resident Keys are the ones that aren't supported. Related KeePassXC PR: https://github.com/keepassxreboot/keepassxc/pull/10283

Passkeys: Fixes invalid error message related to Resident Keys

---

.eslintrc
build.js
dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/background/background_service.js
keepassxc-browser/background/browserAction.js
keepassxc-browser/background/event.js
keepassxc-browser/background/init.js
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/common/global.js
keepassxc-browser/common/global_ui.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js
keepassxc-browser/popups/popup.css
keepassxc-browser/popups/popup.html
keepassxc-browser/popups/popup_functions.js
keepassxc-browser/popups/popup_httpauth.html
keepassxc-browser/popups/popup_login.html
keepassxc-browser/popups/popup_login.js

Adds support for Manifesft V3 for Chromium based browsers. Firefox will be still supporting the V2 version.
V2 manifest is still used as default. Only when building the extension, Chromium will switch to V3 instead.
The manifest configuration will be the following:
- The root `keepassxc-browser` path contains a "common" `manifest.json` file that can be loaded directly with Firefox, and it should also support Chromium based browsers for now.
- New `dist/` path contains separate manifest files for both browsers. Firefox will remain with V2. These are only used when building packages for release.
Progress:
Fixes #1581.

Support for Manifest V3

---

keepassxc-browser/content/ui.js

Hello,
this PR fixes the current calculation of the icon offset relative to input fields.
Especially with large input fields it can happen, that the icon is not placed appropiately. Please refer to my before/after screenshots for a comparison.
**Before:**
**After:**
**Before:**
**After:**

Fix calculation of icon offset

---

keepassxc-browser/_locales/en/messages.json

Mentioned in https://github.com/keepassxreboot/keepassxc/issues/10403:
> At the highest level, "Passkey" isn't a protocol, it is a noun. Proper use includes: "a passkey" or "passkeys". As it is a noun, it is never capitalized (outside of normal capitalization rules for nouns) and is never used by itself.

Passkeys: Adjust translations

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/passkeys-utils.js
keepassxc-browser/content/passkeys.js

Errors should be only thrown if the fallback option is not used. Otherwise it prevents to use the browser/OS level dialog when there are no saved Passkeys in KeePassXC, but user has a Yubikey or other device that is being used to login instead.
Fixes #2140.

Fix forwarding to fallback on errors

---

keepassxc-browser/background/browserAction.js

https://github.com/keepassxreboot/keepassxc-browser/pull/2125 changed the toolbar icon behavior to show number of credentials instead of a small question mark in the bottom right corner. If HTTP Basic Auth has more than one credentials available, the icon is not changed properly.

Fix showing number of credentials with HTTP Basic Auth

---

keepassxc-browser/content/pwgen.js

Caused by https://github.com/keepassxreboot/keepassxc-browser/pull/1966. The `kpxcPasswordDialog` object no longer exists.

Fix filling the next field from password generator

---

dist/manifest_firefox.json
keepassxc-browser/content/passkeys-utils.js

Fixes the Firefox manifest having an incorrect minimum version.
Also adds some compatibility for some older WebAuthn/passkeys servers that are returning COSEAlgorithmIdentifiers as strings instead of integers.

Parse algorithm type as Number(). Fix required Firefox version.

---

keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/passkeys-utils.js
keepassxc-browser/content/passkeys.js

Wraps the response to a proper `PublicKeyCredential` object. The object is passed as a normal object from the content script, and constructed at the injected script side. I had some strange problems when passing `PublicKeyCredential` object directly to the injected script, so this is the safest way to ensure compatibility.
Also fixes showing an error when credential is excluded, which is quite a common case. Even if we just let the lifetime timer run out, user should have some indication why the passkey creation fails.
I tested this with almost every site I have working passkeys. These changes didn't improve the situation with some problematic sites, e.g. Microsoft.
Supports extension JSON changes with https://github.com/keepassxreboot/keepassxc/pull/10615.
Fixes #2173.

Passkeys: Wrap response to PublicKeyCredential

---

CHANGELOG
dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/_locales/ja/messages.json
keepassxc-browser/manifest.json
package-lock.json
package.json

The SHA256 hashes in `content_security_policy` are no longer needed, and our 1.9.0.4 release for Firefox has blocked from review because of these. A new release must be made ASAP.
`sha256-o4BRBtP28Aof7Hm1dUp+wlMic7aYLfwjS3E5vTxthQU=` was added [here](https://github.com/keepassxreboot/keepassxc-browser/pull/1987), and no longer needed after [this](https://github.com/keepassxreboot/keepassxc-browser/pull/1723).
`sha256-4nJ8uLezzRE3SiBFdkVN/uNwV9YTOGCqRXg6AvB5rCY=` was added [here](https://github.com/keepassxreboot/keepassxc-browser/pull/1571), and no longer needed after [this](https://github.com/keepassxreboot/keepassxc-browser/pull/1771).
I'll update the CHANGELOG and translations to this same PR before merge.

Remove obsolete hashed scripts from manifest

---

keepassxc-browser/content/keepassxc-browser.js

Passkey script injection breaks XML formatting with Firefox. If the page is plain XML document, no script should be injected.
Fixes #2198.

Fix XML formatting with Firefox

---

.eslintrc
dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/background/background_service.js
keepassxc-browser/background/browserAction.js
keepassxc-browser/background/offscreen.js
keepassxc-browser/manifest.json
keepassxc-browser/offscreen/offscreen.html
keepassxc-browser/offscreen/offscreen.js

Since the MV3 upgrade, the background script in Chrome does not have a `window`. Attempting to use the monochrome icon when the theme is `system` results in an error.
This uses the offscreen API to work around the issue. Another option is to set the "effective" theme when the options are saved. This would be a poor experience if the user changes the theme (or if their computer is set to automatically change it based on the time of day).
This doesn't close the offscreen document, which I _think_ is ok. I think it will automatically close on its own. I think this is called a lot so it is probably good to keep it around. 🤷

Fix monochrome icon in Chrome when `colorTheme == 'system'` (MV3 fix)

---

keepassxc-browser/content/fill.js

The `passwordFillIsAllowed` function should only do a check. The logging is done in the caller

Remove duplicate notification

---

keepassxc-browser/common/global.js

If e.g. `http://localhost` is set to Site Preferences and all features are disabled, URL's with ports (for example `http://localhost:8000`) are still accepted.
Changed the behavior so that with `http://localhost` all ports are also disabled by default. Single ports can be still ignored if explicitly set with `http://localhost:8000`, but both rules cannot exist simultaneously. Sadly, this removes the possibility to have a global ignore rule but some single ports allowed at the same time.
Fixes #2201.

Ignore all ports by default in Site Preferences

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/content/banner.js

Renames Credential Banner buttons:
- Dismiss -> Cancel
- Dismiss -> Back (when Update is clicked and credential selection dialog is shown)
Related issue: #2216.

Rename Credential Banner buttons

---

keepassxc-browser/content/passkeys-utils.js
keepassxc-browser/content/passkeys.js

Rename all conversion functions to include `kpxc` at the beginning to prevent overriding page's own scripts.
Fixes #2210.

Rename functions to prevent override

---

keepassxc-browser/content/keepassxc-browser.js

Showing a group in the front of credential is not working with the Credential Banner's update menu.
To reproduce:
1) Have _Display the group name in autocomplete list when credentials are from different groups._ enabled in the extension settings.
2) Create credential for the same site in two different groups.
3) Save new credentials manually for the site using e.g. context menu's Save Credentials.
4) Click _Update_.
5) Group name is not shown in the list.
Fixes #2225.

Show group name in Credential Banner's menu when updating a credential

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/content/username-field.js

Minor translation fixes:
- Do not end checkbox labels with `.` in the settings page. (Should be identical with buttons etc.)
- Add `.` after sentences and messages if missing.
- Remove obsolete translations, remove whitespace at the end of translation.
Fixes #2224.
Fixes Username Icon tooltip mentioned in #2226.

Translation fixes

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/content/username-field.js

`div` has no `alt`, so this code is some leftovers.
Fixes #2239.

Remove obsolete alt property from div

---

dist/manifest_chromium.json

Chrome has reserved the current shortcut for "Send Feedback" functionality. It is now changed to <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> for Windows/Linux and <kbd>MacCtrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> for macOS.
Fixes #2115.

Change password fill shortcut with Chrome

---

keepassxc-browser/background/client.js
keepassxc-browser/background/keepass.js

I found that sometimes when calling the reconnect function, it may be called without any parameters, causing both `tab` and `connectionTimeout` to be `undefined`.
https://github.com/keepassxreboot/keepassxc-browser/blob/b0fd415e425d9e37c7826e4c2904e6eaeae6fb4e/keepassxc-browser/background/keepass.js#L798
In this case, message timeout should not be enabled. 
https://github.com/keepassxreboot/keepassxc-browser/blob/b0fd415e425d9e37c7826e4c2904e6eaeae6fb4e/keepassxc-browser/background/keepass.js#L812
Additionally, the default timeout is too short, so it has been extended, which might explain the console output in https://github.com/keepassxreboot/keepassxc-browser/pull/2233#issuecomment-2158049881
Fixes the issue mentioned in #2232.

Extended message timeout and modified the `reconnect` function.

---

keepassxc-browser/background/page.js
keepassxc-browser/content/keepassxc-browser.js

When comparing URL's with the new iframe support, things are not working as planned.
Fixes:
- Do not use `toLowerCase()`. The paths can contain uppercase letters, and we no longer rely just on domains.
- Use `trimURL()` to remove search part of the URL so a proper comparisons can be made.
Fixes the issue mentioned in https://github.com/keepassxreboot/keepassxc-browser/issues/1358#issuecomment-2031388026.

Handle iframe URLs correctly

---

dist/manifest_firefox.json

Hey :)
Tiny, silly, tid bit..
At about:addons at zoom levels 50% and lower (on my 2022 MacBook Air), Firefox looks for a 32px icon, though doesn't find it, as it's not defined.
So it fetches https://addons.mozilla.org/user-media/addon_icons/917/917354-32.png?modified=1648138451
I'd prefer if the same SVG were displayed at all sizes.

Add "missing" icon size for Firefox

---

keepassxc-browser/content/keepassxc-browser.js

Showing group name in compact mode should be shown only if the setting is enabled.
Regression from https://github.com/keepassxreboot/keepassxc-browser/pull/2119.

Fix showing group name in Autocomplete Menu

---

keepassxc-browser/content/fill.js

Regression from https://github.com/keepassxreboot/keepassxc-browser/pull/2107.
The password fill should be prevented at the last part of the fill, inside `kpxcFill.fillInCredentials()`. It should be also checked if the element is actually an input field. If not, we just don't even try to fill the password.
Fixes #2135.

Fix plain text password fill prevention

---

keepassxc-browser/content/keepassxc-browser.js

Regression from #2119. In some cases (reason unknown?) the credential's group is missing. An empty value should be used instead with some added `.?` checks.
Hotfix release is needed for this because multiple people are affected.
Fixes #2260.

Fix credential sorting

---

keepassxc-browser/background/page.js

Iframe's top level domain matching does not always work. If the hostname includes the TLD itself, wrong part of the `hostname` is removed. `lastIndexOf()` must be used instread.
Fixes #2170

Fix iframe TLD matching

---

keepassxc-browser/css/autocomplete.css

On Windows some letters might get cut off with the new Autocomplete Menu style. Couldn't reproduce this with macOS, but the error can be seen in Windows.
Fixes #2268.

Fix line height with the new Autocomplete Menu

---

build.js
package-lock.json
package.json

Removes `zip-a-folder` library and all dependencies for it from the build script. A simple `tar` command is used instead. It is found by default with all major operating systems.

Remove build script dependency

---

keepassxc-browser/css/autocomplete.css

The Autocomplete Menu's `min-width` should be using `em` instead of `rem`.
Fixes #2273.

Fix setting Autocomplete Menu min-width

---

.gitignore
keepassxc-browser/common/global.js
package-lock.json
package.json
playwright.config.ts
tests/content-scripts.spec.ts
tests/global-setup.js
tests/global-setup.ts
tests/global-teardown.js
tests/global-teardown.ts
tests/global.spec.ts
tests/page.spec.ts
tests/tests.js

Makes some updates to tests:
- Update Playwright to the latest version
- Remove dependency to `file-url`. A native method already exists.
- Change all Playwright files to TypeScript. Content script files are still JavaScript files because those are used directly in the `tests.html`
- Move `global.js` tests to a separate file. There's no need to test those with the content scripts.
In the future I'll investigate the possibility to get rid of the content script tests and remake those in a more practical way, where the extension itself is loaded to the test instead as a headless browser. Mocking `kpxc.credentials` etc. could improve the test coverage quite a bit. But here's just the first step.

Update Playwright and improve tests

---

keepassxc-browser/content/autocomplete.js

Brings back setting the `midWidth` to input field's width. Also adjusts the inner items container to keep its size.

Fix Autocomplete Menu widths

---

keepassxc-browser/content/pwgen.js
keepassxc-browser/content/totp-field.js
keepassxc-browser/content/ui.js
keepassxc-browser/content/username-field.js

The wrapper `div` that holds the Shadow DOM for icons should be positioned with `position: absolute` so it prevents possible problems with the page layouts.
Fixes #896.

Fix breaking page layouts

---

keepassxc-browser/css/autocomplete.css
keepassxc-browser/css/colors.css

At some pages scrollbar colors on Autocomplete Menu do not respect the current theme setting. These needs to be set explicitly.
Fixes #2290.

Fix scrollbar colors with Autocomplete Menu

---

keepassxc-browser/content/fields.js

When segmented TOTP fields are identified inside a form, the types are not checked properly. Added the same check that is used in a different situation to this also. This way it's ensured that the input field types are identical.
Fixes #2303.

Fix segmented TOTP field identification

---

keepassxc-browser/background/page.js

If there are multiple entries with identical usernames, the context menu item's ID is also identical, and the duplicate item is not shown. Entry name is appended to the item's ID/name.
Fixes #2299.

Fix attribute filling with identical usernames

---

build.js

Noticed this when releasing the new build. The `tar` will create a parent folder `keepassxc-browser` inside the zip file. There shouldn't be any parent folder. If `tar -C` is used, parent folder is set to `./`, and the file is still not accepted by Google. Using `cd` is an easy way to make this work properly.

Prevent build script for creating a parent folder

---

keepassxc-browser/content/banner.js

If `querySelector()` is unabled to find the Credential Banner (Shadow DOM is tricky), lets just hide the element instead. This prevents user for creating duplicate or possibly empty credentials by accident.
Fixes #2312
Fixes #2320

Hide Credential Banner on exception

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/fields.js

Fixes the following pages in Predefined Sites:
- Apple iCloud login page (cross-origin iframe)
- PayPal's segmented TOTP (patterns stays the same but `inputMode` is not set, we should allow this combination too)
- Patreon's password fill (the content can be wrapped to `innerHTML` instead)

Fix Predefined Sites for some pages

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js
keepassxc-protocol.md

Extension side implementation of https://github.com/keepassxreboot/keepassxc/pull/11260. Adds a new input field for configuring the default group where passkeys are stored.
Will be only enabled for KeePassXC 2.7.10 and newer.

Add configuration option for modifying the passkeys default group

---

keepassxc-browser/content/passkeys.js

Prevent Illegal Invokcation on getPublicKey/getPublicKeyAlgorithm

---

keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/custom-fields-banner.js
keepassxc-browser/content/ui.js

Fixed the coordinate shift caused by css:zoom
```
+ kpxcUI.browserVerUpon128
```
```
```
```
```

Fix the coordinate shift caused by CSS zoom

---

.eslintrc
keepassxc-browser/background/event.js
keepassxc-browser/background/page.js
keepassxc-browser/common/global.js
keepassxc-browser/content/autocomplete.js
keepassxc-browser/content/banner.js
keepassxc-browser/content/custom-fields-banner.js
keepassxc-browser/content/passkeys.js
keepassxc-browser/content/ui.js
keepassxc-browser/css/banner.css

Adds a grab cursor when hovering on Credential or Custom Login Field banner, and allows user to move it to the bottom, or back to the top. If the credential or group selection dialog is open while dragging, its position is changed as well.
Known issues:
The dragging animation is not visible if dragging is canceled, or dragged to the same position where the banner already is. I couldn't find a reliable way to do that. The best solution was to disable the animation for good.
Banner on top (default):
Banner on bottom (after dragging):
Fixes #2327.

Add support for draggable banners

---

.eslintrc
keepassxc-browser/background/event.js
keepassxc-browser/background/keepass.js
keepassxc-browser/common/global.js
keepassxc-browser/content/pwgen.js
keepassxc-browser/options/options.js
tests/global.spec.ts

Refactors the compare version functions:
- Move the actual `compareVersion()` function to `global.js`.
- Rename `keepass.compareVersion()`  to `keepass.compareVersions()` , and allow it to take in an Array for multiple comparisons.
- Add unit tests.

Refactor compare version functions

---

keepassxc-browser/content/passkeys.js

We are overriding `navigator.credentials` but the `store()` function is not handled at all. It must be called normally from the original API endpoint.
Fixes account creation on X/Twitter that throws an exception because the function is not found.

Passkeys: fix navigator.credentials.store override

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/form.js
keepassxc-browser/content/keepassxc-browser.js

Refactors `kpxcForm` for handling pages where possible change password forms are not actually `form` elements, but three different input fields, and the submit button might not even be related to the same container.
If the new `kpxcForm.initCustomForm()` detects three different password fields and there's a form submit button exception found in `kpxcSites`, the fields are stored temporarily and the extension listens for the submit button click.
Refactors `kpxcForm.onSubmit()` to have multiple smaller functions that the new  `onCustomFormSubmit()` can also use:
- `activateCredentialBanner()` handles the form field results and activates the Credential Banner. Originall this code was at the end of `onSubmit()`.
- `getUsernameValue()` returns the username value from selected input field or …

Add support for custom password change forms

---

keepassxc-browser/content/fields.js

Accept non-defined `maxLength` as well with the segmented TOTP detection when input `type` is `text` or `number`.
Fixes an issue with Akamai's 2FA, mentioned in https://github.com/keepassxreboot/keepassxc-browser/issues/1358#issuecomment-2481537485.

Adjust segmented TOTP detection

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/observer-helper.js

Sites made with React often put input fields under `label` element, which is ignored by the Observer Helper. This should be allowed for greater compatibility.
Also adds reddit.com to the improved input fields sites list.
Fixes login popup with e.g. reddit.com.

Allow label on observer

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/content/fill.js

When trying to fill credentials from the Username Icon or from context menu, a specific error message is shown if current database is not connected to KeePassXC.

Show error notification when database is not connected

---

keepassxc-browser/content/observer-helper.js

Adds some additional checks for the functions. Node here can be something else than `Element`, and `getAttribute()` used inside the lowercasewrapper might not be found.
Fixes #2410.

Add checks for TreeWalker filter

---

keepassxc-browser/content/observer-helper.js

Removes the <span> element from ignored nodes list. Input fields can be used inside of those elements.
Fixes #2396.
Manually:
_Go to https://magyarorszag.hu/, switch to English (upper right corner), then click "Login" (on the left side). On the appearing page, choose "Client gate". The appearing page now displays in Hungarian, but the upper input field is the username, the lower is the password field. These fields are completely undetected._
Improved Input Field …

Remove span element from ignored nodes

---

keepassxc-browser/content/keepassxc-browser.js

Fixed values of constants as in [BrowserMessageBuilder.h](https://github.com/keepassxreboot/keepassxc/blob/f2ed4e38409ddc3ae208c57f0015e9c2de9e87de/src/browser/BrowserMessageBuilder.h#L53) or [/background/client.js](https://github.com/keepassxreboot/keepassxc-browser/blob/a277d6c8b9079762d11a23c80584997bd2099766/keepassxc-browser/background/client.js#L31)
Currently the bug does not affect add-on's logic.

Fixed values of constants

---

dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/manifest.json

Google wants this permission to be added. The permission is not listed in https://developer.chrome.com/docs/extensions/reference/permissions-list but handled under `host_permissions`: https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns#special. They didn't provide any detailed info where this should be set, so this is the best bet.
- ✅ Maintenance

Add all_urls permission to manifest files

---

keepassxc-browser/common/sites.js
keepassxc-browser/content/observer-helper.js

A new feature, and a regression from https://github.com/keepassxreboot/keepassxc-browser/pull/2391. Reddit creates a lot of content dynamically while scrolling the page. If possible, Shadow DOM input field query must be restricted on some sites to prevent any slowdowns in the browser.
There could be a better solution for the problem, so this is probably just a temporary workaround.
Manually using a long thread from www.reddit.com.
[NOTE]: # ( Please remove all …

Add exceptions for Shadow DOM input query

---

dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/passkeys-inject.js
keepassxc-browser/content/passkeys-utils.js
keepassxc-browser/content/passkeys.js
keepassxc-browser/manifest.json

Loads passkey injection script at document start. It gives a higher probability to catch WebAuthn requests made by the browser. There are several sites that do this before the document loading is finished.
Also wraps the content of `passkeys.js` inside async so the variables and functions will no leak to the site.
Fixes #2431.
Fixes #2434.
Manually. If Chromium based browser is used, the `manifest_chromium.json` must be copied manually over the default …

Inject passkeys scripts at document_start

---

keepassxc-browser/background/page.js

Continued from https://github.com/keepassxreboot/keepassxc-browser/pull/2366. If managed settings are found, those should be always used, not just when the extension is started for the first time.

Load managed settings always when found

---

keepassxc-browser/content/totp-field.js

Adds an extra check for HTML input `type` when accepting TOTP fields.
Fixes #2444.
Manually.

Add extra check for TOTP field input type

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

Allows editing of Site Preferences table URLs.
When pressing Edit button or double clicking the URL, the cell enters to an edit mode. When the URL differs (and is valid), it can be saved by pressing <kbd>Enter</kbd> or clicking the Save button. Pressing <kbd>Escape</kbd> or clicking Cancel button, the URL returns to the original state.
The input field is using identical validation with "Add URL manually" input.
Fixes #2185 
[NOTE]: # ( Use if available. )
[NOTE]: # ( Do not include screenshots of your actual database credentials! )
[NOTE]: # ( Please describe in detail how you tested your …

Allow editing Site Preferences table

---

dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/manifest.json
package.json

We have been using a "common" `manifest.json` for years for development/debugging that has been working with all browsers. Now when Chromium based browsers have disabled the support for Manifest V2 extensions, this method cannot be no longer used. The following changes are needed:
- Use Chromium's manifest file as the default one.
- Add script command `debug:chromium` for switching to Chromium based V3 manifest file.
- Add script command `debug:firefox` for switching to Firefox based V2 manifest file.
- ✅ New feature (change that adds …

Script modifications for development/debugging

---

dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/manifest.json

URLs containing `.xml` can cause content scripts to be ignored, even if the MIME type is plain HTML. `keepassxc-browser.js` already checks the `contentType` from the document, so it should be enough to rely on that.
Fixes #2505
Manually.

Remove XML URL from exclude list

---

keepassxc-browser/background/event.js
keepassxc-browser/background/page.js
keepassxc-browser/content/keepassxc-browser.js
keepassxc-browser/content/passkeys-inject.js

If a page has been entered to Site Preferences and all features are disabled, the extension should not inject the passkey script to the page.
Manually using https://webauthn.io
- ✅ Bug fix (non-breaking change that fixes an issue))

Disable passkeys script injection if site is ignored

---

keepassxc-browser/background/browserAction.js
keepassxc-browser/background/event.js
keepassxc-browser/background/init.js
keepassxc-browser/background/keepass.js
keepassxc-browser/background/page.js
keepassxc-browser/common/global.js

Sometimes `page.settings` is not loaded before other scripts are doing their job. This can happen on browser launch, after browser update etc. Additional checks are added.
There's some strange delay after browser start before the toolbar icons update. The whole reason for this behavior is kind of weird. When browser starts for the first time, the scripts are initialized in a different order. If the extension is reloaded using `edge://extensions` the order is again the correct one. These changes should ensure the order is kept intact.
Fixes #2507.
[NOTE]: # ( Please describe in detail how you …

Fixes for page object checks and context menu item creation

---

keepassxc-browser/content/keepassxc-browser.js

If user triggers the KeePassXC unlock dialog from the Username Icon and switches the database that will be opened, credentials are not immediately returned to the content scripts. The `_called.retrieveCredentials` state should be only used with the Mutation Observer and no longer with the plain credential retrieval. The credentials are cached for a while in the background script.
Fixes #2468
Manually. Steps to reproduce:
- Have two databases in KeePassXC. Only …

Fix retrieving credentials from changed DB in unlock dialog

---

keepassxc-browser/options/options.js

Firefox 137 and newer finally support opening extension shortcut pages: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands/openShortcutSettings.
The internal shortcuts page must be removed when support for `openShortcutSettings()` hits the Firefox ESR.
Fixes #389.
Manually.
- ✅ New feature (change that adds functionality)

Add support for opening Firefox shortcut settings page

---

keepassxc-browser/content/form.js

When `onSubmit()` is triggered on form, the username field is not always present in the input field list even if it's inside the form object. In this case try to use the first `type=text` input in the form so Credential Banner can be showed after login.
Fixes #2460.
Might also fix another sites that have problems showing the Credential Banner.
Manually. Created a temporary email address for temu.com.
- ✅ …

Improve username input detection with Credential Banner

---

keepassxc-browser/common/sites.js

Adds a submit button exception for OpenAI login page. When entering the password, Apple's button is selected by default.
Fixes #2541
Manually. The site accepts any email and password.

Add submit button exception for OpenAI login page

---

README.md
keepassxc-browser/popups/popup.html

In the following popup:
This link points to id "#_setup_browser_integration" in the "KeePassXC_GettingStarted" document. Currently, the id attribute for the "Browser Integration" section is "#_browser_integration". This commit fixes that.
Also updated the link the README.
[NOTE]: # ( Use if available. )
[NOTE]: # ( Do not include screenshots of your actual database credentials! )
Same screenshot as above.
Tested by navigating to …

Fix browser integration doc link id

---

keepassxc-browser/_locales/en/messages.json
keepassxc-browser/options/options.css
keepassxc-browser/options/options.html

Minor styling improvements for the settings pages:
- Change the color of application name string
- Add border radius to menu selector border
- Add more padding to the tables
- Remove bright table borders on dark theme
- Remove table headers from obvious actions (delete)
- Change Site Preferences' table input field background color on dark theme
- Add some spacing before the table on Site Preferences page
- Change checkboxes to switches on General page
- Change range input thumb color
- Change green button color to be more saturated (The colors don't exactly match with KeePassXC, but that …

Styling improvements

---

keepassxc-browser/background/keepass.js
keepassxc-browser/content/keepassxc-browser.js

The URL passed to Global Auto-Type was incorrect. The function name has been changed while ago, and `getBaseDomainFromUrl()` must be used instead.
The context menu item triggers the command from all iframes in the page, including Google ads etc. It must be restricted with `isIframeAllowed()`. Otherwise the client triggers multiple Global Auto-Type commands to KeePassXC.
Manually.
- ✅ Bug fix (non-breaking …

Fix Global Auto-Type search param

---

.eslintrc
README.md
dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/_locales/en/messages.json
keepassxc-browser/background/init.js
keepassxc-browser/common/global_ui.js
keepassxc-browser/manifest.json
keepassxc-browser/options/getting_started.css
keepassxc-browser/options/getting_started.html
keepassxc-browser/options/getting_started.js
keepassxc-browser/options/options.html
keepassxc-browser/options/options.js

When the extension is installed for the first time, common default settings are shown to user. A lot of issues are made because e.g. HTTP Basic Auth or passkeys option is actually disabled.
The PR also adds support for setting KeePassXC-Browser as a default password manager for browser. Basically it just disables the browser's own internal password manager. This option is added to both Getting Started and Settings pages.
A new permission for `privacy` is needed to access the relevant API.
Fixes #2377
Fixes #2424
[NOTE]: # ( Use if available. )
[NOTE]: # ( Do not include screenshots of your …

Add Getting Started page, and support for default password manager setting

---

dist/manifest_chromium.json
dist/manifest_firefox.json
keepassxc-browser/background/page.js
keepassxc-browser/common/global_ui.js
keepassxc-browser/manifest.json
keepassxc-browser/options/getting_started.js
keepassxc-browser/options/options.js

Moves the new `privacy` permission to `optional_permissions` list. This needs a new setting that is in sync with the permission, otherwise the page tries to use the permission every time on load and would trigger the prompt when querying the default password manager setting from browser. The permission prompt is shown only when trying to change the option for the first time, or denying it and trying again.
I didn't add this option to managed settings.
Related issue thread: #2588
[TIP]:  # ( Also describe how to test the …

Move privacy to optional permissions
