- CHANGELOG
- keepassxc-browser/background/browserAction.js
- keepassxc-browser/background/event.js
- keepassxc-browser/background/httpauth.js
- keepassxc-browser/background/init.js
- keepassxc-browser/background/keepass.js
- keepassxc-browser/background/page.js
- keepassxc-browser/global.js
- keepassxc-browser/keepassxc-browser.css
- keepassxc-browser/keepassxc-browser.js
- keepassxc-browser/manifest.json
- keepassxc-browser/options/options.css
- keepassxc-browser/options/options.html
- keepassxc-browser/options/options.js
- keepassxc-browser/popups/popup.css
- keepassxc-browser/popups/popup.html
- keepassxc-browser/popups/popup.js
- keepassxc-browser/popups/popup_functions.js
- keepassxc-browser/popups/popup_httpauth.html
- keepassxc-browser/popups/popup_httpauth.js
- keepassxc-browser/popups/popup_login.html
- keepassxc-browser/popups/popup_login.js
- keepassxc-browser/popups/popup_multiple-fields.html
- keepassxc-browser/popups/popup_remember.html
- keepassxc-browser/popups/popup_remember.js
Version 0.5.0
Changes:
- Fixed an error when filling only a password
- Credential retrieval is allowed when only one input field is visible (TOTP)
- Asynchronous receiveCredentialsIfNecessary()
- Send triggerUnlock with request that need to popup KeePassXC to front
- Added verifyDatabaseResponse to get_databasehash
- Renamed keepassxc-browser to KeePassXC-Browser
- Removed duplicate retrieve_credentials requests
- Fixed identation
- Added support for credential filling through user interaction when database is closed
> Version 0.5.0

- CHANGELOG
- keepassxc-browser/background/browserAction.js
- keepassxc-browser/background/event.js
- keepassxc-browser/background/httpauth.js
- keepassxc-browser/background/keepass.js
- keepassxc-browser/background/page.js
- keepassxc-browser/global.js
- keepassxc-browser/keepassxc-browser.js
- keepassxc-browser/manifest.json
- keepassxc-browser/options/options.html
0.5.2 (02-02-2018)
=========================
- Choose own credential fields saves the full URL instead of host
- HTTP Auth no longer gets stuck when there are no credentials available
- Added option to show notifications (enabled by default)
- Added notifications for HTTP Auth and saving new credentialsList (new permission needed)
> Version 0.5.2

- keepassxc-browser/options/options.html
Updates the keyboard shortcuts from the options page to match the ones in manifest.json.
> Update keyboard shortcuts from the options page

- keepassxc-browser/options/options.html
Solves https://github.com/keepassxreboot/keepassxc-browser/issues/13.
> Updated copyright texts and Web Store Link

- keepassxc-browser/keepassxc-browser.css
- keepassxc-browser/options/options.css
Adjusted colors and font from options page and password generator dialog. Solves https://github.com/keepassxreboot/keepassxc-browser/issues/12.
> Adjust colors

- .gitignore
- keepassxc-browser/keepassxc-browser.css
- keepassxc-browser/options/options.css
Adds some shadows to options page banner and password generator widget. Makes them to pop out a little better.
> CSS modifications

- keepassxc-browser/keepassxc-browser.js
Fixes listener leaking and calling of unnecessary functions.
Related to https://github.com/keepassxreboot/keepassxc-browser/issues/57 but doesn't solve it.
> Fix listener leaking

- keepassxc-browser/keepassxc-browser.js
If a site has multiple credentials with different TOTP's configured the correct one is picked. Previously only the TOTP from the first credentials were received.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/118.
Related KeePassXC PR: https://github.com/keepassxreboot/keepassxc/pull/1850
> Fixes TOTP filling with multiple credentials

- keepassxc-browser/keepassxc-browser.js
This PR improves detection of username fields on pages there's only username field visible. Also, autocomplete will be enabled for these inputs.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/94
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/36
> Improve detection of username fields

- keepassxc-browser/background/event.js
- keepassxc-browser/background/init.js
- keepassxc-browser/background/keepass.js
Tries reload automatically when KeePassXC is not started.
> Automatic reload

- keepassxc-browser/background/init.js
Fixes https://github.com/keepassxreboot/keepassxc/issues/1765.
> Disable automatic reconnect

- keepassxc-browser/keepassxc-browser.js
Fixes constant checking of new input fields via `getAllFields()` and credential retrieving. Instead inputs are detected from new elements and the element ID is saved to prevent multiple calls to `initCredentialFields`.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/146 and https://github.com/keepassxreboot/keepassxc-browser/issues/145.
> Mutation observer fix

- keepassxc-browser/background/keepass.js
Checks a variable before using.
> Adds check for variable

- keepassxc-browser/keepassxc-browser.js
Domain only option is not working in some cases.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/149.
> Fix save domain only option

- keepassxc-browser/background/browserAction.js
- keepassxc-browser/background/init.js
- keepassxc-browser/background/keepass.js
- keepassxc-browser/options/options.js
- keepassxc-browser/popups/popup_remember.js
With some sites the popup for new/changed credentials didn't show at the first time when the icon is clicked.
Fixes #67.
> Fix showing credential update popup

- keepassxc-browser/keepassxc-browser.js
MutationObserver optimizations introduce a new `cipObserverHelper` object that optimizes the detection of changed/added/removed elements.
Attribute changes that are not modifying `display` or `z-index`are ignored. New elements are stored to `_observerIds` array that prevents credential field initialization to fields that are already detected.
Maximum input fields on one page is limited to 100. After that KeePassXC-Browser doesn't do any detection.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/177.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/171.
> MutationObserver optimizations

- keepassxc-browser/keepassxc-browser.js
Introduces a new function `cipFields.isVisible()`. It is more strict for ignoring any input fields outside the web page, or password fields that are actually hidden. The previous jQuery implementation was not secure enough.
> Improved field ignore

- keepassxc-browser/background/page.js
Returns the function if tab with requested ID is not found.
> Add check to page tab ID

- keepassxc-browser/keepassxc-browser.js
Checks input fields for any `search` values from all attributes. This is needed because only a few pages actually use the standard `type="search"` for input fields.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/186.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/190.
> Ignore search fields

- keepassxc-browser/keepassxc-browser.js
Disables single input fields for now. An opt-in feature will be implemented later.
This also fixes one bug from `isVisible()` that allowed input fields to be detected which contained a CSS class with hidden visibility. Now the check is being done against `getComputedStyle()`.
Fixes: https://github.com/keepassxreboot/keepassxc-browser/issues/193
Fixes: https://github.com/keepassxreboot/keepassxc-browser/issues/192
Fixes: https://github.com/keepassxreboot/keepassxc-browser/issues/187
> Disable single inputs

- keepassxc-browser/background/browserAction.js
One check for undefined was missing from the PR #199.
> Fix undefined check

- keepassxc-browser/keepassxc-browser.js
Checks the closest form for id or className that contains "search".
> Improvements to isSearchField()

- keepassxc-browser/keepassxc-browser.js
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/209.
> Ignore SVG elements

- keepassxc-browser/keepassxc-browser.js
- keepassxc-browser/options/options.html
- keepassxc-browser/options/options.js
- keepassxc-browser/popups/popup.html
- keepassxc-browser/popups/popup_httpauth.html
- keepassxc-browser/popups/popup_login.html
- keepassxc-browser/popups/popup_multiple-fields.html
Renames "Specified credential fields" to "Custom credential fields".
New texts taken from translations PR https://github.com/keepassxreboot/keepassxc-browser/pull/37.
> Rename Specified credential fields to Custom credential fields

- keepassxc-browser/keepassxc-browser.js
> Add check for newValue

- keepassxc-browser/popups/popup.css
Minor CSS adjustments for showing the popup correctly.
> Popup CSS adjustments

- keepassxc-browser/background/browserAction.js
- keepassxc-browser/options/options.html
Allows infinite icon blinking on remember credential popups.
> Allow infinite waiting on remember credentials

- keepassxc-browser/popups/popup.css
- keepassxc-browser/popups/popup_login.html
- keepassxc-browser/popups/popup_login.js
A new input field will show up if more entries are present in popup.
Search matches case insensitively any part of title, unlike autocomplete-like select.
> Added quick filter in popup

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/background/browserAction.js
- keepassxc-browser/background/httpauth.js
- keepassxc-browser/background/init.js
- keepassxc-browser/background/keepass.js
- keepassxc-browser/global.js
- keepassxc-browser/keepassxc-browser.js
- keepassxc-browser/manifest.json
- keepassxc-browser/options/options.html
- keepassxc-browser/popups/popup.html
- keepassxc-browser/popups/popup_httpauth.html
- keepassxc-browser/popups/popup_login.html
- keepassxc-browser/popups/popup_multiple-fields.html
- keepassxc-browser/popups/popup_remember.html
- keepassxc-browser/popups/popup_remember.js
- keepassxc-browser/translate.js
Adds translations to the browser extension. Actual translation work can be done with Transifex.
> Translations

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/keepassxc-browser.js
Fixes a translation and one if condition using old variable name.
> Fix for showing discard message and button when selecting custom login fields

- keepassxc-protocol.md
Updates the protocol page with some fixes that were missing.
> Fixes to keepassxc-protocol

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/keepassxc-browser.js
Added a `Show more` button to be able to select arbitrary custom fields for passwords.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/360.
> fix #360 add `Show more` btn for pwd fields

- keepassxc-browser/background/browserAction.js
- keepassxc-browser/background/event.js
- keepassxc-browser/background/httpauth.js
- keepassxc-browser/background/init.js
- keepassxc-browser/background/keepass.js
- keepassxc-browser/background/page.js
- keepassxc-browser/keepassxc-browser.js
- keepassxc-browser/manifest.json
- keepassxc-browser/options/options.html
- keepassxc-browser/options/options.js
- keepassxc-browser/options/shortcuts.js
- keepassxc-browser/popups/popup.js
- keepassxc-browser/popups/popup_httpauth.js
- keepassxc-browser/popups/popup_login.js
- keepassxc-browser/popups/popup_remember.js
- keepassxc-browser/translate.js
Cleans the code:
- if-else is always on the same line
- Use Unix end-of-line sequences
- Use spaces when passing Objects or arrays
- Use single-line quotes
- Use `const` when possible
> Code cleaning

- keepassxc-browser/keepassxc-browser.js
#391 changed the action names for shortcuts. The main content script was not updated properly.
> Fix shortcuts

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/background/init.js
- keepassxc-browser/keepassxc-browser.css
- keepassxc-browser/keepassxc-browser.js
- keepassxc-browser/manifest.json
- keepassxc-browser/options/options.css
- keepassxc-browser/options/options.html
- keepassxc-browser/options/options.js
- keepassxc-browser/options/shortcuts.html
- keepassxc-browser/options/shortcuts.js
- keepassxc-browser/translate.js
Fixes based on the Accessibility Lab's audit. The contents might still change. Some of the fixes must be also merged to #128.
New features:
- "Choose custom login fields" can now be used from keyboard
- Password generator can be launched from a keyboard shortcut
- Settings page menu items can be accessed from keyboard
- Settings page's modal dialog has always the Ok button focused by default
- Input errors on Settings page are displayed visually
- About page shows link to creating a new GitHub issue
- About page shows debugging info
- Any HTML attribute can now be translated
- Various minor HTML fixes
All color and contrast related issues will be done later when possible themeing is added to the extension with High Contrast and Dark Theme.
High priority:
Normal priority:
Low priority: …
> Accessibility fixes

- keepassxc-browser/_locales/en/messages.json
The previous way of writing this sounded unusual.
> Minor Update messages.json

- keepassxc-browser/keepassxc-browser.js
Because I was freaking out on issue #165 I tried find a solution. Appeared to be the most simple fix ever.
Here is the PR for it :)
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/165.
> Fixed ignored sites in firefox

- keepassxc-browser/background/keepass.js
- keepassxc-browser/content/define.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/pwgen.js
- keepassxc-browser/content/ui.js
Remove the rest of `document` event overrides.
Fixes #494.
Fixes #503.
> Remove document event overrides

- keepassxc-browser/content/keepassxc-browser.js
- Improves the form submit detection by adding a listener to the login button
- Improves the login button detection
Fixes #334.
Fixes #421.
Fixes #515.
> Improve password change detection

- keepassxc-browser/background/keepass.js
Delivers the connected database hashes to `get-databasehash` request, and enables updating the hashes in the response. It's important to update the extension before KeePassXC 2.5.0 release.
Reason for this: database hashes used with the extension are calculated using root group UUID + recycle bin UUID, which causes problems if any recycle bin related changes are made in the database. In these situations the extension thinks the connection has not been made to this database.
KeePassXC side PR: https://github.com/keepassxreboot/keepassxc/pull/3382
> Support for updating legacy database hashes

- package-lock.json
Cloned, installed and npm wanted a version update.
> Update package-lock.json from npm audit fix

- keepassxc-browser/content/keepassxc-browser.js
Support for skipping Auto-Submit.
Related KeePassXC PR: https://github.com/keepassxreboot/keepassxc/pull/3444
> Add support for skip Auto-Submit property

- keepassxc-browser/background/page.js
- keepassxc-browser/content/autocomplete.js
- keepassxc-browser/content/banner.js
- keepassxc-browser/content/define.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/pwgen.js
- keepassxc-browser/content/sites.js
- keepassxc-browser/content/ui.js
- keepassxc-browser/content/username-field.js
- keepassxc-browser/global.js
- Fix a missing `await`
- Fix errors with `define.js`
- General code cleaning
Fixes #569.
> Fix await with TOTP fill, code cleaning

- keepassxc-browser/_locales/en/messages.json
The tense was unusual, updated it to the correct tense.
> Fixed popupUpdateAvailable tense

- keepassxc-browser/background/event.js
- keepassxc-browser/content/autocomplete.js
- keepassxc-browser/content/keepassxc-browser.js
Cleans some of the functions returning Promise. In some cases the arguments were provided as an Array, but not handled as such.
Fixes #645.
> Clean functions returning Promise

- keepassxc-browser/content/keepassxc-browser.js
If an cross-domain iframe is trying to access `window.top.location.href`, `kpxc.initCredentialFields()` returns because a DOMException is thrown.
Instead, use `window.self.location.href` if an exception is thrown. This will use the iframe URL and does the check correctly using `siteMatch()`.
Also, checking the Site Preferences is moved a new function.
Good sites for testing this are:
- https://www.aliexpress.com
- https://www.mysynchrony.com/
Fixes #433.
> Handle cross-domain iframe inputs correctly

- README.md
> Add dev info in README.md

- README.md
Adds the new Microsoft Edge addon link to README.
> Updated Microsoft Edge addon link

- keepassxc-browser/options/options.js
Checking the JSON contents for settings import fails every time.
Fixes #771.
> Fix import settings check

- keepassxc-browser/content/keepassxc-browser.js
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/778.
> Ignore input fields with readOnly set

- keepassxc-browser/background/browserAction.js
- keepassxc-browser/background/event.js
- keepassxc-browser/background/init.js
- keepassxc-browser/background/keepass.js
- keepassxc-browser/background/page.js
- keepassxc-browser/content/autocomplete.js
- keepassxc-browser/content/banner.js
- keepassxc-browser/content/define.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/pwgen.js
- keepassxc-browser/content/totp-field.js
- keepassxc-browser/content/ui.js
- keepassxc-browser/content/username-field.js
- keepassxc-browser/global.js
- keepassxc-browser/options/options.js
- keepassxc-browser/options/shortcuts.js
- keepassxc-browser/popups/popup.js
- keepassxc-browser/popups/popup_functions.js
Basic code cleaning PR for the next release. Removes extra whitespaces, improves readability, adds missing semicolons, changes unnecessary `let` variables to `const` etc.
> Code cleaning for 1.5.5

- keepassxc-browser/options/options.html
- keepassxc-browser/options/shortcuts.html
Allows to identify the tab based on icon
> Add favicon

- keepassxc-browser/options/options.html
- keepassxc-browser/options/options.js
after pressing
and ctrl+v
```
KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 75.0
```
> Add a copy button for version

- keepassxc-browser/css/autocomplete.css
- keepassxc-browser/css/banner.css
- keepassxc-browser/css/colors.css
- keepassxc-browser/options/options.css
- keepassxc-browser/popups/popup.css
Some more adjustments to the new theme:
- Removes extra borders from credential listings (banner and popups)
- Updates the colors from the latest KeePassXC theme PR
> New theme adjustments

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/content/banner.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/ui.js
- keepassxc-browser/content/username-field.js
- keepassxc-browser/options/options.html
- Hide username icon properly when needed (add one extra check)
- Add missing translations
- Some code cleaning
> Bug fixes for 1.6.0.

- keepassxc-browser/options/options.html
Smaller screen
Mobile screen size
> Add menu icons

- keepassxc-browser/content/totp-field.js
> Fix TOTP negative check too strict for (zip|postal)code

- keepassxc-browser/content/banner.js
Add some additional check when saving credentials.
Fixes #841.
> Check undefined when saving credentials

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/content/define.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/css/define.css
Allows to choose a custom TOTP field when choosing custom login fields.
> Choose custom TOTP field

- keepassxc-protocol.md
Maybe this prevents someone from making the same mistake I once did.
> Clarify key pair usages in protocol description

- keepassxc-browser/content/autocomplete.js
- keepassxc-browser/content/ui.js
Hello,
I noticed autocomplete position is incorrect on https://linuxfr.org/
It seems the problem come from relative position on the body element, so I try to  fix it.
> fix autocomplete position when body position is relative

- keepassxc-browser/options/options.js
Removes the separate `options.saveSettingsPromise()` and uses a proper `async/await` for saving every time.
> Simplify options saving process

- .eslintrc
- keepassxc-browser/background/httpauth.js
- keepassxc-browser/content/keepassxc-browser.js
Some small corrections for the next release.
> Final cleaning for 1.6.4

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/options/options.html
Change a unnecessary two part translation to a single one.
> Fix a translation without a parameter

- keepassxc-browser/content/autocomplete.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/username-field.js
For same pages the password fill didn't work anymore. Reason: Promise was not resolved via `await`.
> Add missing awaits for async functions

- keepassxc-browser/content/keepassxc-browser.js
Fix reinitializing MutationObserver on every tab switch.
Fixes #927.
> Fix MutationObserver reinit

- keepassxc-protocol.md
Adds `get-totp` to the protocol document.
> Add get-totp

- keepassxc-browser/content/keepassxc-browser.js
Some small fixes for 1.7.0 release.
- Don't allow the automatic redection to enter a forever-loop.
- Use `document.body` instead of `document`. We are not interested in headers, scripts etc.
- Allow using `getComputedStyle()` for a single style mutation.
- Inspect input fields inside Shadow DOM if added dynamically (great site to test this is https://www.raiplay.it/ ).
> Cleaning for 1.7.0

- README.md
Updates README.md with the current valid URL for setting up browser integration.
> Update README.md with current setup URL

- keepassxc-browser/css/banner.css
> Remove Credential Banner when printing

- keepassxc-browser/common/sites.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/manifest.json
> Add fidelity.com to Predefined Sites

- keepassxc-browser/content/autocomplete.js
> Fix submitting the usernam when selecting from autocomplete list via keyboard

- keepassxc-browser/options/shortcuts.js
Adds code from Firefox's own codebase, which is licenced with MPL 2.0. Sadly, using the `shortcuts.js` directly from `chrome://mozapp` is restricted.
Fixes #1093.
> Improve keyboard shortcuts page

- keepassxc-browser/content/keepassxc-browser.js
> Give TOTP field higher priority than KPH: fields when using action get-totp

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/options/options.css
- keepassxc-browser/options/options.html
Adds a list of Patreon supporters to the extension About tab page.
> Add supporters

- keepassxc-browser/content/define.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/css/define.css
- Allows selecting input fields with less restrictions with `More` option
- Restricts setting the height of internal divs
Fixes #957.
Fixes #1109.
Fixes #1112
> Custom Login Fields fixes

- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/options/shortcuts.js
> Small fixes for 1.7.4

- keepassxc-browser/options/options.js
> Show Win64 platform correctly in About page.

- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/pwgen.js
Adds proper events for filling password from Password Generator.
Fixes #1178.
> Fix password generator fill

- keepassxc-browser/content/keepassxc-browser.js
> Add missing checks for StringFields

- keepassxc-browser/common/sites.js
- keepassxc-browser/content/keepassxc-browser.js
> Add exception for Protonmail's mailbox password input

- .eslintrc
- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/common/global.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/options/options.html
> Ignore Auto-Submit option for Site Preferences

- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/totp-autocomplete.js
- keepassxc-browser/content/totp-field.js
- keepassxc-browser/content/ui.js
> Fill multiple single TOTP fields

- keepassxc-browser/background/event.js
- keepassxc-browser/options/options.js
Remove a previously hard-coded snapshot version from if-sentence.
> Fix version error message on options page

- keepassxc-browser/content/totp-field.js
Tested with web-ext, works fine
> Add "2fpin" to acceptedOTPFields to fix #1291

- keepassxc-browser/content/keepassxc-browser.js
- Keeps the login ID for updating TOTP lists
- Fixes a check for credential list
Fixes #1311.
Fixes #1328.
>  TOTP filling fixes

- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/manifest.json
- package.json
This broke some sites. Causes more problems than does any good.
Fixes #1379.
> Revert form visibility check

- keepassxc-browser/content/define.js
- keepassxc-browser/manifest.json
https://github.com/keepassxreboot/keepassxc-browser/pull/1386 broke this one. Also moved the selector to Shadow DOM as well.
> Fix Custom Fields selector CSS

- keepassxc-browser/content/totp-field.js
> Fix LinkedIn TOTP field detection

- keepassxc-browser/background/event.js
- keepassxc-browser/background/keepass.js
- keepassxc-browser/background/page.js
- keepassxc-browser/common/global.js
- keepassxc-browser/options/options.html
- keepassxc-browser/options/options.js
> Switch update check default interval to Never

- keepassxc-browser/content/ui.js
- keepassxc-browser/css/colors.css
Fixes CSS issues with the current development branch:
- With Firefox Shadow DOM cannot find CSS Variables if those are not defined with `:host`.
- Notifications are not displaying correctly because `notification.css` is no longer part of default content scripts. Notifications are now added to Shadow DOM also.
> Fix CSS issues

- keepassxc-browser/common/sites.js
- keepassxc-browser/content/ui.js
Apple has made some changes that caused errors when trying to detect the password field. This should fix it.
> Fix Apple login page

- CHANGELOG
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Upgrades necessary files to version 1.7.10.1.
> Upgrade version

- keepassxc-browser/_locales/bg/messages.json
- keepassxc-browser/_locales/et/messages.json
- keepassxc-browser/_locales/he/messages.json
- keepassxc-browser/_locales/nl/messages.json
- keepassxc-browser/_locales/ro/messages.json
- keepassxc-browser/_locales/sl/messages.json
Adds missing translations:
- Bulgarian
- Estonian
- Hebrew
- Dutch (nl)
- Romanian
- Slovenian
Fixes #1463.
> Add missing translations

- keepassxc-browser/content/totp-field.js
Fixes username field detection for example dhl.de.
> Add inputMode check for 2FA field detection

- keepassxc-browser/common/sites.js
Add new predefided sites to list:
- HP Support
- FNAC
> Add new predefined sites

- keepassxc-browser/content/banner.js
> Trim username when displaying Credential Banner

- keepassxc-browser/common/sites.js
- keepassxc-browser/content/keepassxc-browser.js
Fix detecting form submit button properly for Auto-Submit with Amazon AWS.
Fixes #1240.
> Fix Auto-Submit with Amazon AWS

- keepassxc-browser/content/keepassxc-browser.js
Fix a missing check that luckily rarely hits.
> Fix check for undefined combination variable

- keepassxc-browser/content/pwgen.js
- keepassxc-browser/content/username-field.js
- keepassxc-browser/css/pwgen.css
> Fix removing icon from parent/document

- keepassxc-browser/content/autocomplete.js
- keepassxc-browser/content/credential-autocomplete.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/totp-autocomplete.js
- keepassxc-browser/css/autocomplete.css
This refactors the autocomplete list code quite a bit. Sorry I didn't split it into well defined commits but a big reason for that is these changes kinda snowballed as I went along. I kept finding things that I wanted to change.
I was mostly annoyed at the first item always being selected, which makes submitting user-entered text more annoying than it should be. I don't want the enter key to pick from the autocomplete list if the text I entered doesn't match. So this turns the text you enter into a search string that is used to find the element you want. It will even `scrollIntoView` the item if the list is scrolled. If the text you enter doesn't match any item, then it will deselect the item in the list and the enter key will not interfere.
Summary of changes:
- You can now type in the …
> Autocomplete search feature

- keepassxc-browser/background/client.js
- keepassxc-browser/background/keepass.js
- keepassxc-protocol.md
Solves error responses going out-of-sync with https://github.com/keepassxreboot/keepassxc/pull/7404.
> Handle requestID with error responses

- keepassxc-browser/_locales/en/messages.json
> Adjust auto-fill warning message

- CHANGELOG
Making a release today, so let's update the changelog already.
> Update changelog for 1.8.0

- keepassxc-browser/background/client.js
- keepassxc-browser/background/keepass.js
Adds support for https://github.com/keepassxreboot/keepassxc/pull/8273.
> Send RequestId for supporting asynchronous Access Control dialog

- keepassxc-browser/_locales/en/messages.json
> Fix typos in the main translation file

- keepassxc-browser/content/fill.js
- Fixes fill from popup in some cases.
- Returns Auto-Submit sooner if not used.
> Small fixes for 1.8.2

- CHANGELOG
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Forgot this from the previous PR.
> Update changelog and version numbers

- CHANGELOG
- keepassxc-browser/background/keepass.js
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Let's add this back with a version check before 2.7.2 is released.
> Add Request ID with version check

- .tx/config
The resource configuration has been changed: https://github.com/transifex/cli#migrating-from-older-versions-of-the-client
> Update Transifex configuration file

- keepassxc-browser/content/autocomplete.js
Autocomplete Menu is not updated automatially on certain situations.
To reproduce:
- Have "Search from all databases" enabled in KeePassXC
- Open two databases and go to some login page
- Close the first database
- KeePassXC is switched to the second database, extension popup menu is updated
- Autocomplete Menu still shows the old credentials from the closed database
Previously the div was updated only when creating it. Now it's updated every time the menu is opened.
> Fix updating Autocomplete Menu on database close

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/background/page.js
Increases the default value for Credential Banner redirects from 1 to 3.
> Increase default redirect value from 1 to 3

- keepassxc-browser/content/keepassxc-browser.js
Add a simple check for readonly fields.
Fixes #1840.
> Do not fill readonly fields

- keepassxc-browser/content/autocomplete.js
- keepassxc-browser/css/autocomplete.css
Shows Autocomplete Menu above the input field if there's no space below.
https://user-images.githubusercontent.com/24570482/221574374-aa479288-76d8-4219-90de-7ee3721235e5.mp4
Fixes #604.
> Add support for showing Autocomplete Menu on top

- keepassxc-browser/content/fields.js
Improves the segmented TOTP field detection.
In some cases the extension has already identified the segmented fields as separate TOTP fields to a six different `combination` objects. This situation is not currently handled at all.
The solution identifies if six TOTP fields are in the combination, changes that to a single combination object with `totpInputs` and removes the six field from the original combination array.
Related issue in comment: https://github.com/keepassxreboot/keepassxc-browser/issues/1358#issuecomment-1529743424
> Improvements to segmented TOTP field detection

- keepassxc-browser/_locales/en/messages.json
Changes the Basic HTTP Auth message in the Options page.
> Change HTTP Auth message

- keepassxc-browser/common/sites.js
- keepassxc-browser/content/observer-helper.js
Adds `https://www.patreon.com/login` to predefined sites. Add a site exception for the password fill.
> Add Patreon to Predefined Sites

- keepassxc-browser/background/event.js
- keepassxc-browser/options/options.js
Some erros are being seen when removing a connection from the options page. Additional checks added.
Fixes #2004.
> Add some extra checks when removing a connection

- .eslintrc
- package.json
Add linting to scripts. Can be run using `npm run lint`.
> Add eslint to scripts

- keepassxc-browser/content/keepassxc-browser.js
`kpxc.retrieveCredentials()` is missing the check for cross-domain iframes.
> Disallow iframes from another domain

- keepassxc-browser/background/client.js
- keepassxc-browser/content/banner.js
The Credential Banner's container has an ID that can possibly collide with page content.
Includes some cleanup (Prettier/eslint).
Fixes #2065.
> Rename Credential Banner container id

- CHANGELOG
- keepassxc-browser/_locales/bg/messages.json
- keepassxc-browser/_locales/de/messages.json
- keepassxc-browser/_locales/el/messages.json
- keepassxc-browser/_locales/es/messages.json
- keepassxc-browser/_locales/hu/messages.json
- keepassxc-browser/_locales/nb/messages.json
- keepassxc-browser/_locales/nl/messages.json
- keepassxc-browser/_locales/pt_BR/messages.json
- keepassxc-browser/_locales/uk/messages.json
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Updates CHANGELOG, JSON files and updates translations for 1.8.11.
> Update to 1.8.11

- keepassxc-browser/popups/popup_login.js
Fixes showing the filter input for logins in the extension popup.
Fixes #2136.
> Fix showing login filter in the popup

- CHANGELOG
- dist/manifest_chromium.json
- dist/manifest_firefox.json
- keepassxc-browser/_locales/de/messages.json
- keepassxc-browser/_locales/it/messages.json
- keepassxc-browser/_locales/ja/messages.json
- keepassxc-browser/_locales/nl/messages.json
- keepassxc-browser/_locales/pt_BR/messages.json
- keepassxc-browser/_locales/ru/messages.json
- keepassxc-browser/_locales/tr/messages.json
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Updates translations, version numbers and CHANGELOG for 1.9.0.3.
> Update to 1.9.0.3

- CHANGELOG
- dist/manifest_chromium.json
- dist/manifest_firefox.json
- keepassxc-browser/_locales/es/messages.json
- keepassxc-browser/_locales/pt_BR/messages.json
- keepassxc-browser/_locales/pt_PT/messages.json
- package-lock.json
- package.json
Updates CHANGELOG, version numbers and translations for 1.9.0.4.
> Update to 1.9.0.4

- keepassxc-browser/content/passkeys-utils.js
https://github.com/keepassxreboot/keepassxc/pull/10384 is merged, so these can be removed.
> Passkeys: Remove temporary exceptions

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/content/pwgen.js
- keepassxc-browser/content/totp-field.js
- keepassxc-browser/options/options.html
- keepassxc-browser/popups/popup.html
- keepassxc-browser/popups/popup_httpauth.html
- keepassxc-browser/popups/popup_login.html
Changes:
- Adds button titles to options page and popup.
- Modifies the names to be identical in every place.
- Removes obsolete `alt` properties from `div` icons.
Fixes #2241.
Fixes #2242
> Fix more translations

- CHANGELOG
- dist/manifest_chromium.json
- dist/manifest_firefox.json
- keepassxc-browser/_locales/bg/messages.json
- keepassxc-browser/_locales/de/messages.json
- keepassxc-browser/_locales/it/messages.json
- keepassxc-browser/_locales/ja/messages.json
- keepassxc-browser/_locales/nl/messages.json
- keepassxc-browser/_locales/pt_BR/messages.json
- keepassxc-browser/_locales/ru/messages.json
- keepassxc-browser/_locales/sv/messages.json
- keepassxc-browser/_locales/zh_CN/messages.json
- keepassxc-browser/_locales/zh_TW/messages.json
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Update CHANGELOG, manifest files and offline translations for 1.9.1.1.
> Update to 1.9.1.1

- dist/manifest_chromium.json
- dist/manifest_firefox.json
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/manifest.json
Make sure XML content types or files are not affected by the extension content scripts.
Fixes #2286.
> Fix XML formatting

- .eslintrc
- keepassxc-browser/common/sites.js
- keepassxc-browser/content/keepassxc-browser.js
Adds support for Improved Input Field Detection when checking Predefined Sites. With this we can finally get rid of dozens of reports with Chase's website.
> Add Improved Input Field Detection to Predefined Sites feature

- CHANGELOG
- dist/manifest_chromium.json
- dist/manifest_firefox.json
- keepassxc-browser/_locales/es/messages.json
- keepassxc-browser/_locales/hu/messages.json
- keepassxc-browser/_locales/it/messages.json
- keepassxc-browser/_locales/ja/messages.json
- keepassxc-browser/_locales/ru/messages.json
- keepassxc-browser/_locales/tr/messages.json
- keepassxc-browser/_locales/uk/messages.json
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Update CHANGELOG, manifest files and offline translations for 1.9.2
> Update to 1.9.2

- keepassxc-browser/common/sites.js
- keepassxc-browser/content/fields.js
- keepassxc-browser/content/fill.js
- keepassxc-browser/content/form.js
- keepassxc-browser/content/keepassxc-browser.js
- keepassxc-browser/content/observer-helper.js
- keepassxc-browser/content/ui.js
Oops. This functions needs to be used against the element itself, not the `nodeName`. A new release must be made after this has been merged.
> Fix nodeName check

- CHANGELOG
- dist/manifest_chromium.json
- dist/manifest_firefox.json
- keepassxc-browser/_locales/bg/messages.json
- keepassxc-browser/_locales/ru/messages.json
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Updates CHANGELOG, version information and offline translations for 1.9.3.
> Update to 1.9.3

- keepassxc-browser/common/sites.js
- keepassxc-browser/content/ui.js
> Add icon offset exception to Royal Bank Canada

- keepassxc-browser/_locales/en/messages.json
Resolves translator feedback from Transifex
> Fix base translation wording

- keepassxc-browser/content/observer-helper.js
Includes the following improvementes:
- Instead of traversing each child with `.childNodes()` rely on the TreeWalker API for retrieving all elements under the target.
- Add a proper check for `Element` Shadow DOM using `openOrClosedShadowRoot` and `dom.openOrClosedShadowRoot()`.
- Support Shadow DOM's under Document Fragments.
A few test sites:
https://e.sfcu.org/sfcuonline/uux.aspx#/login
https://login.minid.no/ (accesible via https://venterom.skatteetaten.no/?c=digdir&e=skatteetaten&t=https%3A%2F%2Fskatt.skatteetaten.no%2Fweb%2Fminside%2F)
Fixes #446.
> Better identification for Shadow DOM in Improved Input Field Detection

- dist/manifest_chromium.json
- dist/manifest_firefox.json
- keepassxc-browser/background/page.js
- keepassxc-browser/managed_storage.json
- keepassxc-browser/manifest.json
Adds support for distributing global settings to the extension using [3rdparty policy](https://mozilla.github.io/policy-templates/#3rdparty). Includes a new `managed_storage.json` file that describes the settings that can be set. The schema file must be formatted correctly or the extension does not start because of failed validation.
Easiest way to test this was to use `web-ext` with Firefox that had the policy JSON file added. Just made sure I deleted all storage data from the temporary extension before launching it again. That caused the `settings` to be an empty Object, and the getter for managed settings will be called.
Example `policy.json` file:
```
{
"policies": {
"3rdparty": {
"Extensions": {
"keepassxc-browser@keepassxc.org": {
"settings": {
"defined-custom-fields": { …
```
> Add support for managed settings using 3rdparty policy

- CHANGELOG
- dist/manifest_chromium.json
- dist/manifest_firefox.json
- keepassxc-browser/_locales/he/messages.json
- keepassxc-browser/_locales/hu/messages.json
- keepassxc-browser/_locales/id/messages.json
- keepassxc-browser/_locales/pt_PT/messages.json
- keepassxc-browser/_locales/ru/messages.json
- keepassxc-browser/_locales/uk/messages.json
- keepassxc-browser/_locales/zh_TW/messages.json
- keepassxc-browser/manifest.json
- package-lock.json
- package.json
Updates CHANGELOG, manifest files and offline translations for 1.9.5.
> Update to 1.9.5

- keepassxc-browser/common/sites.js
Add predefined Improved Input Field Detection for Qt's and Max's login pages.
Fixes #2397
> Add some predefined sites

- keepassxc-browser/options/options.js
The passkeys fallback checkbox should be disabled when passkeys feature is unchecked.
Relates to #2377, but does not fix it.
Manually.
> Disable passkeys fallback checkbox when needed

- keepassxc-browser/common/sites.js
Adds old.reddit.com login page redirect to Predefined Sites.
Fixes #2410.
Manually.
> Fix old.reddit.com login page

- keepassxc-browser/_locales/en/messages.json
- keepassxc-browser/content/pwgen.js
- keepassxc-browser/content/totp-field.js
- keepassxc-browser/content/username-field.js
- keepassxc-browser/options/options.html
Allows user to hide any icon with shift+click. Added an info alert to options page.
Fixes #2456
Fixes #2476
Manually.
- ✅ New feature (change that adds functionality)
> Add support for hiding icons manually

- keepassxc-browser/options/options.js
There's no need to restrict this to lowercase.
Fixes #2481.
Manually.
> Remove .toLowerCase() from manual URL add

- keepassxc-browser/common/sites.js
- keepassxc-browser/content/form.js
- keepassxc-browser/content/keepassxc-browser.js
Improves automatic submit button detection when there's no form in the site. An exception from Predefined Sites is used, or `button[type=submit]` or `button.login` is searched instead.
https://www.reddit.com login form submit button detection should be fixed with this.
> Improve submit button detection

- keepassxc-browser/background/page.js
Adds an extra checks for managed API. There has been some reports that certain browser versions (in distros etc.) might have these disabled, or `isFirefox()` fails for some reason (invalid/changed user agent?).
Manually.
> Add check for managed API

- CHANGELOG
- README.md
Adds a mention about permissions and permission changes to README and CHANGELOG.
- ✅ Documentation (non-code change)
> Add mentions about missing permissions and permission changes

- README.md
URL has been invalid due to infra changes of Transifex two years ago
> chore(i18n): Fix URL of Transifx
